package com.nospace.birdsfoods.crafting;

import com.nospace.birdsfoods.items.BirdItems;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.ShapedOreRecipe;
import net.minecraftforge.oredict.ShapelessOreRecipe;

public class BirdCrafting {

   public static final void init() {
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.dandelion_salad), (Object[])(new Object[]{"listAllflower", "listAllflower"})));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.spring_salad), new Object[]{"cropLettuce", "listAllveggie", "listAllmushroom"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cobb_salad), new Object[]{"cropLettuce", "foodBoiledegg", "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.potato_soup), new Object[]{"cropPotato", "cropPotato", Items.bowl}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.raw_bacon, 2), new Object[]{Items.porkchop}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fruit_salad), new Object[]{"listAllfruit", "listAllfruit", "listAllfruit"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.yogurt, 2), new Object[]{"listAllmushroom", "listAllmilk"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheese), new Object[]{"listAllmilk", Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pita), new Object[]{"cropWheat", "cropWheat"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pita), new Object[]{"foodFlour", "foodFlour"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sliced_lamb, 2), new Object[]{"foodCookedmutton"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chopped_chicken, 2), new Object[]{Items.cooked_chicken}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.gyro), new Object[]{BirdItems.sliced_lamb, "foodYogurt", BirdItems.pita}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.raw_fingers, 2), new Object[]{Items.chicken}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_salad), new Object[]{BirdItems.chopped_chicken, "foodYogurt", BirdItems.empty_sandwich}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.potato_salad), new Object[]{Items.baked_potato, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.potato_salad), new Object[]{Items.baked_potato, "foodMayo"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.empty_sandwich, 2), new Object[]{Items.bread}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheese_sandwich), new Object[]{BirdItems.empty_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.egg_sandwich), new Object[]{"foodScrambledegg", BirdItems.empty_sandwich}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.egg_sandwich), new Object[]{"foodBoiledegg", BirdItems.empty_sandwich}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.egg_sandwich), new Object[]{"foodFriedegg", BirdItems.empty_sandwich}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.egg_and_cheese_sandwich), new Object[]{BirdItems.egg_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.egg_and_cheese_sandwich), new Object[]{"foodBoiledegg", BirdItems.empty_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.egg_and_cheese_sandwich), new Object[]{"foodScrambledegg", BirdItems.empty_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.egg_and_cheese_sandwich), new Object[]{"foodFriedegg", BirdItems.empty_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.egg_and_cheese_sandwich), new Object[]{BirdItems.cheese_sandwich, "foodBoiledegg"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.egg_and_cheese_sandwich), new Object[]{BirdItems.cheese_sandwich, "foodScrambledegg"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.egg_and_cheese_sandwich), new Object[]{BirdItems.cheese_sandwich, "foodFriedegg"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_and_egg_sandwich), new Object[]{"foodBoiledegg", BirdItems.empty_sandwich, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_and_egg_sandwich), new Object[]{"foodScrambledegg", BirdItems.empty_sandwich, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_and_egg_sandwich), new Object[]{"foodFriedegg", BirdItems.empty_sandwich, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_and_egg_sandwich), new Object[]{BirdItems.bacon_sandwich, "foodBoiledegg"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_and_egg_sandwich), new Object[]{BirdItems.bacon_sandwich, "foodScrambledegg"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_and_egg_sandwich), new Object[]{BirdItems.bacon_sandwich, "foodFriedegg"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_and_egg_sandwich), new Object[]{BirdItems.egg_sandwich, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_egg_and_cheese_sandwich), new Object[]{"foodBoiledegg", BirdItems.empty_sandwich, "foodBacon", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_egg_and_cheese_sandwich), new Object[]{"foodScrambledegg", BirdItems.empty_sandwich, "foodBacon", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_egg_and_cheese_sandwich), new Object[]{"foodFriedegg", BirdItems.empty_sandwich, "foodBacon", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_egg_and_cheese_sandwich), new Object[]{BirdItems.bacon_sandwich, "foodBoiledegg", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_egg_and_cheese_sandwich), new Object[]{BirdItems.bacon_sandwich, "foodScrambledegg", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_egg_and_cheese_sandwich), new Object[]{BirdItems.bacon_sandwich, "foodFriedegg", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_egg_and_cheese_sandwich), new Object[]{BirdItems.egg_sandwich, "foodBacon", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_egg_and_cheese_sandwich), new Object[]{"foodBoiledegg", BirdItems.cheese_sandwich, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_egg_and_cheese_sandwich), new Object[]{"foodScrambledegg", BirdItems.cheese_sandwich, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_egg_and_cheese_sandwich), new Object[]{"foodFriedegg", BirdItems.cheese_sandwich, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_egg_and_cheese_sandwich), new Object[]{BirdItems.bacon_and_egg_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_egg_and_cheese_sandwich), new Object[]{BirdItems.egg_and_cheese_sandwich, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_sandwich), new Object[]{"foodBacon", BirdItems.empty_sandwich}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_and_cheese_sandwich), new Object[]{"foodBacon", BirdItems.empty_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_and_cheese_sandwich), new Object[]{BirdItems.bacon_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_and_cheese_sandwich), new Object[]{"foodBacon", BirdItems.cheese_sandwich}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.raw_barbecue_chicken, 2), new Object[]{Items.chicken, BirdItems.molasses}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.raw_barbecue_pork, 2), new Object[]{Items.porkchop, BirdItems.molasses}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_bbq_sandwich), new Object[]{BirdItems.empty_sandwich, BirdItems.barbecue_pork}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_bbq_sandwich), new Object[]{BirdItems.empty_sandwich, BirdItems.barbecue_chicken}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.ground_beef, 2), new Object[]{Items.beef}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.hamburger), new Object[]{BirdItems.burger, BirdItems.empty_sandwich}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheeseburger), new Object[]{BirdItems.burger, BirdItems.empty_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheeseburger), new Object[]{BirdItems.burger, BirdItems.cheese_sandwich}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_hamburger), new Object[]{BirdItems.hamburger, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_hamburger), new Object[]{BirdItems.burger, BirdItems.empty_sandwich, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_hamburger), new Object[]{BirdItems.burger, BirdItems.bacon_sandwich}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_cheeseburger), new Object[]{BirdItems.cheeseburger, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_cheeseburger), new Object[]{BirdItems.hamburger, "foodCheese", "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_cheeseburger), new Object[]{BirdItems.burger, "foodCheese", BirdItems.empty_sandwich, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_cheeseburger), new Object[]{BirdItems.burger, BirdItems.cheese_sandwich, "foodBacon"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_cheeseburger), new Object[]{BirdItems.burger, BirdItems.bacon_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_cheeseburger), new Object[]{BirdItems.burger, BirdItems.bacon_and_cheese_sandwich}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cold_chips, 3), new Object[]{"cropPotato", "cropPotato"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_and_chips), new Object[]{"foodFries", "listAllfishcooked", Items.paper}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.raw_crisps, 2), new Object[]{"cropPotato"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sliced_steak, 2), new Object[]{Items.cooked_beef}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.steak_sandwich), new Object[]{BirdItems.empty_sandwich, BirdItems.sliced_steak}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesesteak), new Object[]{BirdItems.empty_sandwich, "foodCheese", BirdItems.sliced_steak}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesesteak), new Object[]{BirdItems.steak_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesesteak), new Object[]{BirdItems.cheese_sandwich, BirdItems.sliced_steak}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_meat, 2), new Object[]{"listAllveggie", "listAllveggie", "listAllveggie", "listAllveggie"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_hamburger), new Object[]{BirdItems.empty_sandwich, BirdItems.veggie_meat}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_cheeseburger), new Object[]{BirdItems.empty_sandwich, BirdItems.veggie_meat, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_cheeseburger), new Object[]{BirdItems.veggie_hamburger, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_cheeseburger), new Object[]{BirdItems.cheese_sandwich, BirdItems.veggie_meat}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_gyro), new Object[]{BirdItems.pita, BirdItems.veggie_meat, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.raw_fish_sticks, 2), new Object[]{Items.fish}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.stuffed_potato), new Object[]{Items.baked_potato, "foodBacon", "foodYogurt", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_jerky, 3), new Object[]{Items.beef, Items.beef}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chocolate_bar), new Object[]{"listAllmilk", new ItemStack(Items.dye, 1, 3), Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.ice_cream), new Object[]{"listAllmilk", Items.snowball, Items.snowball, Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.ice_cream_sundae), new Object[]{"foodIcecream", BirdItems.hot_fudge}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.dagwood), new Object[]{BirdItems.fish_fillet, "listAllveggie", BirdItems.chopped_chicken, BirdItems.sliced_steak, "foodBacon", "foodBoiledegg", "foodCheese", Items.bread, Items.bread}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.dagwood), new Object[]{BirdItems.fish_fillet, "listAllveggie", BirdItems.chopped_chicken, BirdItems.sliced_steak, "foodBacon", "foodScrambledegg", "foodCheese", Items.bread, Items.bread}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.dagwood), new Object[]{BirdItems.fish_fillet, "listAllveggie", BirdItems.chopped_chicken, BirdItems.sliced_steak, "foodBacon", "foodFriedegg", "foodCheese", Items.bread, Items.bread}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_soba), new Object[]{"foodNoodles", BirdItems.sliced_steak}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_soba), new Object[]{"foodNoodles", BirdItems.chopped_chicken}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_soba), new Object[]{"foodNoodles", BirdItems.fish_fillet}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_soba), new Object[]{"foodNoodles", "listAllveggie", "listAllveggie", "listAllveggie"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fugu), new Object[]{new ItemStack(Items.fish, 1, 3)}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sashimi, 2), new Object[]{new ItemStack(Items.fish, 1, 1)}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.apple_pie_a_la_mode), new Object[]{BirdItems.apple_pie, "foodIcecream"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.smothered_potato), new Object[]{Items.baked_potato, "foodYogurt", "foodCheese", "listAllmushroom"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_fillet, 2), new Object[]{"listAllfishcooked"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sliced_cactus, 3), new Object[]{Blocks.cactus, Blocks.cactus}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pumpkin_soup), new Object[]{"cropPumpkin", Items.bowl, "listAllmilk"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sliced_beets, 4), new Object[]{"cropBeetroot", "cropBeetroot"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.candied_beets), new Object[]{"cropBeetroot", Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cannibal_sandwich), new Object[]{BirdItems.empty_sandwich, BirdItems.ground_beef}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.real_cannibal_sandwich), new Object[]{BirdItems.empty_sandwich, Items.rotten_flesh}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.alfredo_sauce), new Object[]{"listAllmilk", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fettucine_alfredo), new Object[]{"foodPasta", BirdItems.alfredo_sauce}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.mushroom_alfredo), new Object[]{BirdItems.fettucine_alfredo, "listAllmushroom", "listAllmushroom"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.mushroom_alfredo), new Object[]{"foodPasta", BirdItems.alfredo_sauce, "listAllmushroom", "listAllmushroom"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_alfredo), new Object[]{BirdItems.fettucine_alfredo, BirdItems.chopped_chicken}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_alfredo), new Object[]{"foodPasta", BirdItems.alfredo_sauce, BirdItems.chopped_chicken}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.seafood_alfredo), new Object[]{BirdItems.fettucine_alfredo, BirdItems.fish_fillet}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.seafood_alfredo), new Object[]{"foodPasta", BirdItems.alfredo_sauce, BirdItems.fish_fillet}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.squid_ink_pasta), new Object[]{"foodPasta", new ItemStack(Items.dye, 1, 0)}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.buffalo_chicken, 2), new Object[]{Items.cooked_chicken, Items.blaze_powder}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.buffalo_chicken), new Object[]{BirdItems.chicken_fingers, Items.blaze_powder}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.buffalo_chicken, 2), new Object[]{BirdItems.chicken_fingers, BirdItems.chicken_fingers, Items.blaze_powder}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.buffalo_chicken), new Object[]{BirdItems.chopped_chicken, Items.blaze_powder}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.buffalo_chicken, 2), new Object[]{BirdItems.chopped_chicken, BirdItems.chopped_chicken, Items.blaze_powder}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.curry_sauce), new Object[]{"foodYogurt", "foodCurrypowder", "listAllmilk"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.curry_sauce), new Object[]{"foodYogurt", Items.blaze_powder, "listAllmilk"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_vindaloo), new Object[]{BirdItems.curry_sauce, Items.cooked_beef}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.lamb_vindaloo), new Object[]{BirdItems.curry_sauce, "foodCookedmutton"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_tikka), new Object[]{BirdItems.curry_sauce, Items.cooked_chicken}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.paneer_tikka), new Object[]{BirdItems.curry_sauce, "foodCheese", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_curry), new Object[]{BirdItems.curry_sauce, Items.cooked_porkchop}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_curry), new Object[]{BirdItems.curry_sauce, Items.cooked_fished}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_curry), new Object[]{BirdItems.curry_sauce, new ItemStack(Items.cooked_fished, 1, 1)}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veg_curry), new Object[]{BirdItems.curry_sauce, "listAllveggie", "listAllveggie"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veg_sandwich), new Object[]{BirdItems.empty_sandwich, "listAllveggie", "listAllveggie", "listAllveggie"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veg_sandwich), new Object[]{BirdItems.empty_sandwich, "listAllveggie", "listAllveggie", "listAllveggie", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veg_sandwich), new Object[]{BirdItems.cheese_sandwich, "listAllveggie", "listAllveggie", "listAllveggie"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veg_sandwich), new Object[]{BirdItems.veg_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.hotcakes), new Object[]{"egg", "cropWheat", Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.waffles), new Object[]{"egg", "cropWheat", Items.sugar, Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.berry_hotcakes), new Object[]{"egg", "cropWheat", Items.sugar, "cropChorusfruit"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.berry_hotcakes), new Object[]{"egg", "foodFlour", Items.sugar, "cropChorusfruit"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.berry_hotcakes), new Object[]{"egg", "cropWheat", Items.sugar, "listAllberry"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.berry_hotcakes), new Object[]{"egg", "foodFlour", Items.sugar, "listAllberry"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.berry_waffles), new Object[]{"egg", "cropWheat", Items.sugar, Items.sugar, "cropChorusfruit"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.berry_waffles), new Object[]{"egg", "foodFlour", Items.sugar, Items.sugar, "cropChorusfruit"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.berry_waffles), new Object[]{"egg", "cropWheat", Items.sugar, Items.sugar, "listAllberry"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.berry_waffles), new Object[]{"egg", "foodFlour", Items.sugar, Items.sugar, "listAllberry"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.choc_hotcakes), new Object[]{"egg", "cropWheat", Items.sugar, new ItemStack(Items.dye, 1, 3)}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.choc_waffles), new Object[]{"egg", "cropWheat", Items.sugar, Items.sugar, new ItemStack(Items.dye, 1, 3)}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.hotcakes_with_syrup), (Object[])(new Object[]{BirdItems.hotcakes, "foodSyrup"})));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.waffles_syrup), new Object[]{BirdItems.waffles, "foodSyrup"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.berry_hotcakes_syrup), new Object[]{BirdItems.berry_hotcakes, "foodSyrup"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.berry_waffles_syrup), new Object[]{BirdItems.berry_waffles, "foodSyrup"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.choc_hotcakes_syrup), new Object[]{BirdItems.choc_hotcakes, "foodSyrup"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.choc_waffles_syrup), new Object[]{BirdItems.choc_waffles, "foodSyrup"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pumpkin_curry), new Object[]{BirdItems.curry_sauce, "cropPumpkin", "cropPumpkin"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.apple_juice), new Object[]{"cropApple", Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.carrot_juice), new Object[]{"cropCarrot", Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.melon_juice), new Object[]{"cropMelon", Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beet_juice), new Object[]{"cropBeetroot", Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cactus_juice), new Object[]{Blocks.cactus, Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bottle_of_milk, 3), new Object[]{Items.milk_bucket, Items.glass_bottle, Items.glass_bottle, Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bottle_of_milk, 3), new Object[]{"listAllseed", "listAllseed", "listAllseed", "listAllseed", "listAllseed", "listAllwater", Items.glass_bottle, Items.glass_bottle, Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.herbal_tea), new Object[]{"listAllflower", Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sweet_tea), new Object[]{BirdItems.herbal_tea, Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.iced_tea), new Object[]{BirdItems.herbal_tea, Items.snowball}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sweet_iced_tea), new Object[]{BirdItems.herbal_tea, Items.sugar, Items.snowball}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sweet_iced_tea), new Object[]{BirdItems.sweet_tea, Items.snowball}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sweet_iced_tea), new Object[]{BirdItems.iced_tea, Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.milk_tea), new Object[]{BirdItems.herbal_tea, "listAllmilk"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sweet_milk_tea), new Object[]{BirdItems.herbal_tea, "listAllmilk", Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sweet_milk_tea), new Object[]{BirdItems.milk_tea, Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sweet_milk_tea), new Object[]{BirdItems.sweet_tea, "listAllmilk"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chocolate_milk), new Object[]{"listAllmilk", BirdItems.hot_fudge}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.apple_cider), new Object[]{"foodApplejuice", Items.fermented_spider_eye}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.melon_wine), new Object[]{"foodMelonjuice", Items.fermented_spider_eye}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beer), new Object[]{"cropWheat", "cropWheat", Items.fermented_spider_eye, Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beer), new Object[]{"foodFlour", "foodFlour", Items.fermented_spider_eye, Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beet_liquor), new Object[]{"foodBeetjuice", Items.fermented_spider_eye}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.vodka), new Object[]{"cropPotato", "cropPotato", Items.fermented_spider_eye, Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.poitin), new Object[]{Items.poisonous_potato, BirdItems.molasses, Items.fermented_spider_eye, Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.umeshu), new Object[]{"cropPlum", Items.fermented_spider_eye, Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.umeshu), new Object[]{"cropChorusfruit", Items.fermented_spider_eye, Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.rum), new Object[]{BirdItems.molasses, BirdItems.molasses, Items.fermented_spider_eye, Items.glass_bottle}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.tequila), new Object[]{BirdItems.cactus_juice, Items.fermented_spider_eye}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.scumble), new Object[]{BirdItems.apple_cider, Items.nether_wart, Items.blaze_powder, Blocks.snow}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.spiced_beef, 2), new Object[]{Items.beef, Items.blaze_powder}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.spiced_chicken, 2), new Object[]{Items.chicken, Items.blaze_powder}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.spiced_fish, 2), new Object[]{Items.fish, Items.blaze_powder}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.spiced_pork, 2), new Object[]{Items.porkchop, Items.blaze_powder}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.spiced_veggies), new Object[]{BirdItems.veggie_meat, Items.blaze_powder}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco), new Object[]{BirdItems.empty_taco, BirdItems.ancho_beef}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco), new Object[]{BirdItems.empty_taco, BirdItems.ancho_chicken}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco), new Object[]{BirdItems.empty_taco, BirdItems.ancho_fish}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco), new Object[]{BirdItems.empty_taco, BirdItems.ancho_pork}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco), new Object[]{BirdItems.empty_taco, BirdItems.ancho_veggies}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_beef_taco), new Object[]{BirdItems.beef_taco, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_beef_taco), new Object[]{BirdItems.empty_taco, BirdItems.ancho_beef, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_taco), new Object[]{BirdItems.chicken_taco, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_taco), new Object[]{BirdItems.empty_taco, BirdItems.ancho_chicken, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_fish_taco), new Object[]{BirdItems.fish_taco, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_fish_taco), new Object[]{BirdItems.empty_taco, BirdItems.ancho_fish, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_pork_taco), new Object[]{BirdItems.pork_taco, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_pork_taco), new Object[]{BirdItems.empty_taco, BirdItems.ancho_pork, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veggie_taco), new Object[]{BirdItems.veggie_taco, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veggie_taco), new Object[]{BirdItems.empty_taco, BirdItems.ancho_veggies, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_with_cream), new Object[]{BirdItems.beef_taco, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_with_cream), new Object[]{BirdItems.empty_taco, BirdItems.ancho_beef, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_with_cream), new Object[]{BirdItems.chicken_taco, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_with_cream), new Object[]{BirdItems.empty_taco, BirdItems.ancho_chicken, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_with_cream), new Object[]{BirdItems.fish_taco, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_with_cream), new Object[]{BirdItems.empty_taco, BirdItems.ancho_fish, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_with_cream), new Object[]{BirdItems.pork_taco, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_with_cream), new Object[]{BirdItems.empty_taco, BirdItems.ancho_pork, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_with_cream), new Object[]{BirdItems.veggie_taco, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_with_cream), new Object[]{BirdItems.empty_taco, BirdItems.ancho_veggies, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_with_greens), new Object[]{BirdItems.beef_taco, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_with_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_beef, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_with_greens), new Object[]{BirdItems.chicken_taco, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_with_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_chicken, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_with_greens), new Object[]{BirdItems.fish_taco, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_with_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_fish, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_with_greens), new Object[]{BirdItems.pork_taco, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_with_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_pork, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_with_greens), new Object[]{BirdItems.veggie_taco, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_with_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_veggies, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_beef_taco_with_cream), new Object[]{BirdItems.beef_taco, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_beef_taco_with_cream), new Object[]{BirdItems.empty_taco, BirdItems.ancho_beef, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_beef_taco_with_cream), new Object[]{BirdItems.cheesy_beef_taco, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_beef_taco_with_cream), new Object[]{BirdItems.beef_taco_with_cream, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_taco_with_cream), new Object[]{BirdItems.chicken_taco, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_taco_with_cream), new Object[]{BirdItems.cheesy_chicken_taco, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_taco_with_cream), new Object[]{BirdItems.chicken_taco_with_cream, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_taco_with_cream), new Object[]{BirdItems.empty_taco, BirdItems.ancho_chicken, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_fish_taco_with_cream), new Object[]{BirdItems.fish_taco, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_fish_taco_with_cream), new Object[]{BirdItems.cheesy_fish_taco, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_fish_taco_with_cream), new Object[]{BirdItems.fish_taco_with_cream, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_fish_taco_with_cream), new Object[]{BirdItems.empty_taco, BirdItems.ancho_fish, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_pork_taco_with_cream), new Object[]{BirdItems.pork_taco, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_pork_taco_with_cream), new Object[]{BirdItems.cheesy_pork_taco, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_pork_taco_with_cream), new Object[]{BirdItems.pork_taco_with_cream, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_pork_taco_with_cream), new Object[]{BirdItems.empty_taco, BirdItems.ancho_pork, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veggie_taco_with_cream), new Object[]{BirdItems.veggie_taco, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veggie_taco_with_cream), new Object[]{BirdItems.cheesy_veggie_taco, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veggie_taco_with_cream), new Object[]{BirdItems.veggie_taco_with_cream, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veggie_taco_with_cream), new Object[]{BirdItems.empty_taco, BirdItems.ancho_veggies, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_beef_taco_with_greens), new Object[]{BirdItems.beef_taco, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_beef_taco_with_greens), new Object[]{BirdItems.cheesy_beef_taco, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_beef_taco_with_greens), new Object[]{BirdItems.beef_taco_with_greens, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_beef_taco_with_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_beef, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_taco_with_greens), new Object[]{BirdItems.chicken_taco, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_taco_with_greens), new Object[]{BirdItems.cheesy_chicken_taco, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_taco_with_greens), new Object[]{BirdItems.chicken_taco_with_greens, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_taco_with_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_chicken, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_fish_taco_with_greens), new Object[]{BirdItems.fish_taco, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_fish_taco_with_greens), new Object[]{BirdItems.cheesy_fish_taco, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_fish_taco_with_greens), new Object[]{BirdItems.fish_taco_with_greens, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_fish_taco_with_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_fish, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_pork_taco_with_greens), new Object[]{BirdItems.pork_taco, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_pork_taco_with_greens), new Object[]{BirdItems.cheesy_pork_taco, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_pork_taco_with_greens), new Object[]{BirdItems.pork_taco_with_greens, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_pork_taco_with_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_pork, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veggie_taco_with_greens), new Object[]{BirdItems.veggie_taco, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veggie_taco_with_greens), new Object[]{BirdItems.cheesy_veggie_taco, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veggie_taco_with_greens), new Object[]{BirdItems.veggie_taco_with_greens, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_veggie_taco_with_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_veggies, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_with_cream_and_greens), new Object[]{BirdItems.beef_taco, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_with_cream_and_greens), new Object[]{BirdItems.beef_taco_with_cream, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_with_cream_and_greens), new Object[]{BirdItems.beef_taco_with_greens, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_with_cream_and_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_beef, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_with_cream_and_greens), new Object[]{BirdItems.chicken_taco, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_with_cream_and_greens), new Object[]{BirdItems.chicken_taco_with_cream, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_with_cream_and_greens), new Object[]{BirdItems.chicken_taco_with_greens, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_with_cream_and_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_chicken, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_with_cream_and_greens), new Object[]{BirdItems.fish_taco, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_with_cream_and_greens), new Object[]{BirdItems.fish_taco_with_cream, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_with_cream_and_greens), new Object[]{BirdItems.fish_taco_with_greens, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_with_cream_and_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_fish, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_with_cream_and_greens), new Object[]{BirdItems.pork_taco, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_with_cream_and_greens), new Object[]{BirdItems.pork_taco_with_cream, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_with_cream_and_greens), new Object[]{BirdItems.pork_taco_with_greens, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_with_cream_and_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_pork, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_with_cream_and_greens), new Object[]{BirdItems.veggie_taco, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_with_cream_and_greens), new Object[]{BirdItems.veggie_taco_with_cream, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_with_cream_and_greens), new Object[]{BirdItems.veggie_taco_with_greens, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_with_cream_and_greens), new Object[]{BirdItems.empty_taco, BirdItems.ancho_veggies, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_supreme), new Object[]{BirdItems.beef_taco, "foodCheese", "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_supreme), new Object[]{BirdItems.cheesy_beef_taco, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_supreme), new Object[]{BirdItems.beef_taco_with_cream, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_supreme), new Object[]{BirdItems.beef_taco_with_greens, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_supreme), new Object[]{BirdItems.cheesy_beef_taco_with_greens, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_supreme), new Object[]{BirdItems.cheesy_beef_taco_with_cream, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_supreme), new Object[]{BirdItems.beef_taco_with_cream_and_greens, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.beef_taco_supreme), new Object[]{BirdItems.empty_taco, BirdItems.ancho_beef, "foodCheese", "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_supreme), new Object[]{BirdItems.chicken_taco, "foodCheese", "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_supreme), new Object[]{BirdItems.cheesy_chicken_taco, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_supreme), new Object[]{BirdItems.chicken_taco_with_cream, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_supreme), new Object[]{BirdItems.chicken_taco_with_greens, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_supreme), new Object[]{BirdItems.cheesy_chicken_taco_with_greens, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_supreme), new Object[]{BirdItems.cheesy_chicken_taco_with_cream, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_supreme), new Object[]{BirdItems.chicken_taco_with_cream_and_greens, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_taco_supreme), new Object[]{BirdItems.empty_taco, BirdItems.ancho_chicken, "foodCheese", "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_supreme), new Object[]{BirdItems.fish_taco, "foodCheese", "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_supreme), new Object[]{BirdItems.cheesy_fish_taco, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_supreme), new Object[]{BirdItems.fish_taco_with_cream, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_supreme), new Object[]{BirdItems.fish_taco_with_greens, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_supreme), new Object[]{BirdItems.cheesy_fish_taco_with_greens, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_supreme), new Object[]{BirdItems.cheesy_fish_taco_with_cream, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_supreme), new Object[]{BirdItems.fish_taco_with_cream_and_greens, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_taco_supreme), new Object[]{BirdItems.empty_taco, BirdItems.ancho_fish, "foodCheese", "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_supreme), new Object[]{BirdItems.pork_taco, "foodCheese", "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_supreme), new Object[]{BirdItems.cheesy_pork_taco, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_supreme), new Object[]{BirdItems.pork_taco_with_cream, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_supreme), new Object[]{BirdItems.pork_taco_with_greens, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_supreme), new Object[]{BirdItems.cheesy_pork_taco_with_greens, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_supreme), new Object[]{BirdItems.cheesy_pork_taco_with_cream, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_supreme), new Object[]{BirdItems.pork_taco_with_cream_and_greens, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pork_taco_supreme), new Object[]{BirdItems.empty_taco, BirdItems.ancho_pork, "foodCheese", "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_supreme), new Object[]{BirdItems.veggie_taco, "foodCheese", "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_supreme), new Object[]{BirdItems.cheesy_veggie_taco, "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_supreme), new Object[]{BirdItems.veggie_taco_with_cream, "foodCheese", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_supreme), new Object[]{BirdItems.veggie_taco_with_greens, "foodCheese", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_supreme), new Object[]{BirdItems.cheesy_veggie_taco_with_greens, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_supreme), new Object[]{BirdItems.cheesy_veggie_taco_with_cream, "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_supreme), new Object[]{BirdItems.veggie_taco_with_cream_and_greens, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veggie_taco_supreme), new Object[]{BirdItems.empty_taco, BirdItems.ancho_veggies, "foodCheese", "foodYogurt", "cropLettuce"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.taako), new Object[]{BirdItems.beef_taco_supreme, BirdItems.chicken_taco_supreme, BirdItems.fish_taco_supreme, BirdItems.pork_taco_supreme, BirdItems.veggie_taco_supreme, BirdItems.tequila}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.taako), new Object[]{BirdItems.veggie_taco_supreme, BirdItems.veggie_taco_supreme, BirdItems.veggie_taco_supreme, BirdItems.veggie_taco_supreme, BirdItems.veggie_taco_supreme, BirdItems.tequila}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_sandwich), new Object[]{BirdItems.empty_sandwich, BirdItems.chopped_chicken}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chicken_sandwich), new Object[]{BirdItems.empty_sandwich, BirdItems.chicken_fingers}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.buffalo_chicken_sandwich), new Object[]{BirdItems.buffalo_chicken, BirdItems.empty_sandwich}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_sandwich), new Object[]{BirdItems.chicken_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_sandwich), new Object[]{BirdItems.empty_sandwich, BirdItems.chopped_chicken, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_sandwich), new Object[]{BirdItems.empty_sandwich, BirdItems.chicken_fingers, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_sandwich), new Object[]{BirdItems.cheese_sandwich, BirdItems.chopped_chicken}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chicken_sandwich), new Object[]{BirdItems.cheese_sandwich, BirdItems.chicken_fingers}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_buffalo_chicken_sandwich), new Object[]{BirdItems.buffalo_chicken_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_buffalo_chicken_sandwich), new Object[]{BirdItems.cheese_sandwich, BirdItems.buffalo_chicken}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_buffalo_chicken_sandwich), new Object[]{BirdItems.empty_sandwich, BirdItems.buffalo_chicken, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.sliced_ham, 2), new Object[]{Items.cooked_porkchop}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.ham_sandwich), new Object[]{BirdItems.empty_sandwich, BirdItems.sliced_ham}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.ham_and_cheese_sandwich), new Object[]{BirdItems.empty_sandwich, BirdItems.sliced_ham, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.ham_and_cheese_sandwich), new Object[]{BirdItems.ham_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.ham_and_cheese_sandwich), new Object[]{BirdItems.cheese_sandwich, BirdItems.sliced_ham}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.mashed_potato), new Object[]{Items.baked_potato, "listAllmilk", "foodButter"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.mashed_potato_gravy), new Object[]{BirdItems.mashed_potato, "foodGravy"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.gravy, 2), new Object[]{"cropWheat", "foodButter", "foodMeat"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.gravy, 2), new Object[]{"foodFlour", "foodButter", "foodMeat"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.gravy, 2), new Object[]{"cropWheat", "foodButter", "listAllveggie", "listAllveggie", "listAllveggie", "listAllveggie"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.gravy, 2), new Object[]{"foodFlour", "foodButter", "listAllveggie", "listAllveggie", "listAllveggie", "listAllveggie"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.gravy), new Object[]{"cropWheat", "foodButter", "listAllveggie", "listAllveggie"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.gravy), new Object[]{"foodFlour", "foodButter", "listAllveggie", "listAllveggie"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.gravy), new Object[]{"cropWheat", "foodButter", "foodHalfmeat"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.gravy), new Object[]{"foodFlour", "foodButter", "foodHalfmeat"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.gravy, 2), new Object[]{"cropWheat", "foodButter", "foodHalfmeat", "foodHalfmeat"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.gravy, 2), new Object[]{"foodFlour", "foodButter", "foodHalfmeat", "foodHalfmeat"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.egg_salad), new Object[]{BirdItems.empty_sandwich, "foodBoiledegg", "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.egg_salad), new Object[]{BirdItems.empty_sandwich, "foodBoiledegg", "foodMayo"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_salad), new Object[]{BirdItems.empty_sandwich, BirdItems.fish_fillet, "foodYogurt"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.fish_salad), new Object[]{BirdItems.empty_sandwich, BirdItems.fish_fillet, "foodMayo"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.breakfast_burrito), new Object[]{BirdItems.empty_taco, "foodBacon", "foodCheese", "foodScrambledegg"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.breakfast_burrito), new Object[]{BirdItems.empty_taco, BirdItems.veggie_meat, "foodCheese", "foodScrambledegg"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chip_sandwich), new Object[]{BirdItems.empty_sandwich, "foodFries"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chip_sandwich), new Object[]{BirdItems.empty_sandwich, "foodFries", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chip_sandwich), new Object[]{BirdItems.cheese_sandwich, "foodFries"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chip_sandwich), new Object[]{BirdItems.chip_sandwich, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheesy_chip_sandwich), new Object[]{BirdItems.empty_sandwich, BirdItems.cheese_fries}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cheese_fries), new Object[]{"foodFries", "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.poutine), new Object[]{"foodFries", "foodCheese", "foodGravy"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.poutine), new Object[]{BirdItems.cheese_fries, "foodGravy"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chili_fries), new Object[]{"foodFries", BirdItems.chili}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chili_cheese_fries), new Object[]{"foodFries", "foodCheese", BirdItems.chili}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chili_cheese_fries), new Object[]{BirdItems.chili_fries, "foodCheese"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.chili_cheese_fries), new Object[]{BirdItems.cheese_fries, BirdItems.chili}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cincinnati_chili), new Object[]{"foodPasta", BirdItems.chili}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.hot_chili), new Object[]{BirdItems.chili, Items.blaze_powder, Items.blaze_powder, Items.blaze_powder, Items.blaze_powder}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.hot_chili), new Object[]{BirdItems.chili, "cropChili", "cropChili", "cropChili", "cropChili"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.plum_pudding), new Object[]{BirdItems.rum, "cropPlum", "egg", Items.sugar, "cropWheat", "cropWheat", "listAllmilk"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.plum_pudding), new Object[]{BirdItems.rum, "cropChorusfruit", "egg", Items.sugar, "cropWheat", "cropWheat", "listAllmilk"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.meat_pizza), new Object[]{BirdItems.pizza, "foodPizzameat", "foodPizzameat"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.veg_pizza), new Object[]{BirdItems.pizza, "listAllveggie", "listAllveggie", "listAllveggie"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pizza_supreme), new Object[]{BirdItems.pizza, "listAllveggie", "listAllveggie", "listAllveggie", "foodPizzameat", "foodPizzameat"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pizza_supreme), new Object[]{BirdItems.meat_pizza, "listAllveggie", "listAllveggie", "listAllveggie"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pizza_supreme), new Object[]{BirdItems.veg_pizza, "foodPizzameat", "foodPizzameat"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.butter), new Object[]{"listAllmilk", "listAllmilk"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.jam), new Object[]{Items.sugar, "slimeball", "listAllfruit"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.buttered_toast), new Object[]{BirdItems.toast, "foodButter"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.jammy_toast), new Object[]{BirdItems.toast, "foodJam"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.jammy_buttered_toast), new Object[]{BirdItems.toast, "foodJam", "foodButter"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.jammy_buttered_toast), new Object[]{BirdItems.jammy_toast, "foodButter"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.jammy_buttered_toast), new Object[]{BirdItems.buttered_toast, "foodJam"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_pancakes), new Object[]{"egg", "cropWheat", "foodBacon", Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.bacon_pancakes_syrup), new Object[]{BirdItems.bacon_pancakes, "foodSyrup"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pumpkin_spice_latte), new Object[]{"cropPumpkin", "listAllmilk", Items.sugar, Items.glowstone_dust}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pumpkin_bread), new Object[]{"cropPumpkin", "cropWheat", "cropWheat", Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.pumpkin_bread), new Object[]{"cropPumpkin", "foodFlour", "foodFlour", Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.shortbread_cookie), new Object[]{"cropWheat", "foodButter", Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.shortbread_cookie), new Object[]{"foodFlour", "foodButter", Items.sugar}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cookie_dough), new Object[]{"cropWheat", "cropWheat", "foodButter", Items.sugar, "egg", new ItemStack(Items.dye, 1, 3)}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.cookie_dough), new Object[]{"foodFlour", "foodFlour", "foodButter", Items.sugar, new ItemStack(Items.dye, 1, 3)}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.mac_and_cheese), new Object[]{"cropWheat", "foodCheese", "foodButter", "foodPasta", "listAllmilk"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(BirdItems.mac_and_cheese), new Object[]{"foodFlour", "foodCheese", "foodButter", "foodPasta", "listAllmilk"}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Items.poisonous_potato), new Object[]{"cropPotato", Blocks.red_mushroom}));
      GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Items.fermented_spider_eye), new Object[]{Items.poisonous_potato, Blocks.brown_mushroom, Items.sugar}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.apple_pie), new Object[]{"ABA", "CCC", Character.valueOf('A'), "cropApple", Character.valueOf('B'), Items.sugar, Character.valueOf('C'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.apple_pie), new Object[]{"ABA", "CCC", Character.valueOf('A'), "cropApple", Character.valueOf('B'), Items.sugar, Character.valueOf('C'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.buckwheat_noodles), new Object[]{"A", "A", "A", Character.valueOf('A'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.buckwheat_noodles), new Object[]{"A", "A", "A", Character.valueOf('A'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.rabbit_pie), new Object[]{" A ", "BCD", "EEE", Character.valueOf('A'), "foodCookedrabbit", Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.rabbit_pie), new Object[]{" A ", "BCD", "EEE", Character.valueOf('A'), "foodCookedrabbit", Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.chicken_pot_pie), new Object[]{" A ", "BCD", "EEE", Character.valueOf('A'), Items.cooked_chicken, Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.chicken_pot_pie), new Object[]{" A ", "BCD", "EEE", Character.valueOf('A'), Items.cooked_chicken, Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.beef_stew), new Object[]{" A ", "BCD", " E ", Character.valueOf('A'), Items.cooked_beef, Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), Items.bowl}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.shepherds_pie), new Object[]{" A ", "BCD", "EEE", Character.valueOf('A'), "foodCookedmutton", Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.shepherds_pie), new Object[]{" A ", "BCD", "EEE", Character.valueOf('A'), "foodCookedmutton", Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.quiche), new Object[]{"CEM", "W W", Character.valueOf('C'), "foodCheese", Character.valueOf('E'), "egg", Character.valueOf('M'), "listAllmilk", Character.valueOf('W'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.quiche), new Object[]{"CEM", "W W", Character.valueOf('C'), "foodCheese", Character.valueOf('E'), "egg", Character.valueOf('M'), "listAllmilk", Character.valueOf('W'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.green_quiche), new Object[]{"CEM", "WAW", Character.valueOf('C'), "foodCheese", Character.valueOf('E'), "egg", Character.valueOf('M'), "listAllmilk", Character.valueOf('W'), "cropWheat", Character.valueOf('A'), "listAllgreenveggie"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.green_quiche), new Object[]{"CEM", "WAW", Character.valueOf('C'), "foodCheese", Character.valueOf('E'), "egg", Character.valueOf('M'), "listAllmilk", Character.valueOf('W'), "foodFlour", Character.valueOf('A'), "listAllgreenveggie"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.fish_quiche), new Object[]{"CEM", "WAW", Character.valueOf('C'), "foodCheese", Character.valueOf('E'), "egg", Character.valueOf('M'), "listAllmilk", Character.valueOf('W'), "cropWheat", Character.valueOf('A'), BirdItems.fish_fillet}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.fish_quiche), new Object[]{"CEM", "WAW", Character.valueOf('C'), "foodCheese", Character.valueOf('E'), "egg", Character.valueOf('M'), "listAllmilk", Character.valueOf('W'), "foodFlour", Character.valueOf('A'), BirdItems.fish_fillet}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.bacon_quiche), new Object[]{"CEM", "WAW", Character.valueOf('C'), "foodCheese", Character.valueOf('E'), "egg", Character.valueOf('M'), BirdItems.bottle_of_milk, Character.valueOf('W'), "cropWheat", Character.valueOf('A'), "foodBacon"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.bacon_quiche), new Object[]{"CEM", "WAW", Character.valueOf('C'), "foodCheese", Character.valueOf('E'), "egg", Character.valueOf('M'), BirdItems.bottle_of_milk, Character.valueOf('W'), "foodFlour", Character.valueOf('A'), "foodBacon"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.mushroom_quiche), new Object[]{"CEM", "WAW", " B ", Character.valueOf('C'), "foodCheese", Character.valueOf('E'), "egg", Character.valueOf('M'), "listAllmilk", Character.valueOf('W'), "cropWheat", Character.valueOf('A'), "listAllmushroom", Character.valueOf('B'), "listAllmushroom"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.mushroom_quiche), new Object[]{"CEM", "WAW", " B ", Character.valueOf('C'), "foodCheese", Character.valueOf('E'), "egg", Character.valueOf('M'), "listAllmilk", Character.valueOf('W'), "foodFlour", Character.valueOf('A'), "listAllmushroom", Character.valueOf('B'), "listAllmushroom"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.cottage_pie), new Object[]{" A ", "BCD", "EEE", Character.valueOf('A'), Items.cooked_beef, Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.cottage_pie), new Object[]{" A ", "BCD", "EEE", Character.valueOf('A'), Items.cooked_beef, Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.fish_pie), new Object[]{" A ", "BCD", "EEE", Character.valueOf('A'), Items.cooked_fished, Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.fish_pie), new Object[]{" A ", "BCD", "EEE", Character.valueOf('A'), Items.cooked_fished, Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.pasta), new Object[]{" A ", "BBB", Character.valueOf('A'), "egg", Character.valueOf('B'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.pasta), new Object[]{" A ", "BBB", Character.valueOf('A'), "egg", Character.valueOf('B'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.empty_taco, 2), new Object[]{"A A", " A ", Character.valueOf('A'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.empty_taco, 2), new Object[]{"A A", " A ", Character.valueOf('A'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.empty_taco, 2), new Object[]{"A A", " A ", Character.valueOf('A'), "cropCorn"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.veg_pie), new Object[]{" C ", "BCD", "EEE", Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.veg_pie), new Object[]{" C ", "BCD", "EEE", Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.veg_stew), new Object[]{" C ", "BCD", " E ", Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), Items.baked_potato, Character.valueOf('D'), "listAllmushroom", Character.valueOf('E'), Items.bowl}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Items.cake, 1), new Object[]{"AAA", "BEB", "CCC", Character.valueOf('A'), "listAllmilk", Character.valueOf('B'), Items.sugar, Character.valueOf('C'), "cropWheat", Character.valueOf('E'), "egg"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.chicken_noodle_soup), new Object[]{" A ", "BCD", " E ", Character.valueOf('A'), BirdItems.chopped_chicken, Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), "foodPasta", Character.valueOf('D'), "listAllveggie", Character.valueOf('E'), Items.bowl}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.chili), new Object[]{" A ", "BCD", " E ", Character.valueOf('A'), Items.blaze_powder, Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), "foodHalfmeat", Character.valueOf('D'), "listAllveggie", Character.valueOf('E'), Items.bowl}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.chili), new Object[]{" A ", "BCD", " E ", Character.valueOf('A'), "cropChilipepper", Character.valueOf('B'), "listAllveggie", Character.valueOf('C'), "foodHalfmeat", Character.valueOf('D'), "listAllveggie", Character.valueOf('E'), Items.bowl}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.pizza), new Object[]{"BAB", "EEE", Character.valueOf('B'), "foodCheese", Character.valueOf('A'), "listAllmilk", Character.valueOf('E'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.pizza), new Object[]{"BAB", "EEE", Character.valueOf('B'), "foodCheese", Character.valueOf('A'), "listAllmilk", Character.valueOf('E'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.pizza), new Object[]{"BAB", "EEE", Character.valueOf('B'), "foodCheese", Character.valueOf('A'), "cropTomato", Character.valueOf('E'), "cropWheat"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.pizza), new Object[]{"BAB", "EEE", Character.valueOf('B'), "foodCheese", Character.valueOf('A'), "cropTomato", Character.valueOf('E'), "foodFlour"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.bacone), new Object[]{"BCD", "AEA", " A ", Character.valueOf('A'), "foodBacon", Character.valueOf('B'), "foodMashedpotato", Character.valueOf('C'), "foodGravy", Character.valueOf('D'), "foodCheese", Character.valueOf('E'), "foodScrambledegg"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.ice_cream_bacone), new Object[]{"BCD", "AEA", " A ", Character.valueOf('A'), "foodBacon", Character.valueOf('B'), "foodCookie", Character.valueOf('C'), "foodChocolatesauce", Character.valueOf('D'), "foodCookie", Character.valueOf('E'), "foodIcecream"}));
      GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(BirdItems.ice_cream_bacone), new Object[]{"B D", "AEA", " A ", Character.valueOf('A'), "foodBacon", Character.valueOf('B'), "foodCookie", Character.valueOf('D'), "foodCookie", Character.valueOf('E'), BirdItems.ice_cream_sundae}));
      GameRegistry.addSmelting(BirdItems.raw_bacon, new ItemStack(BirdItems.bacon), 0.35F);
      GameRegistry.addSmelting(BirdItems.raw_fingers, new ItemStack(BirdItems.chicken_fingers), 0.35F);
      GameRegistry.addSmelting(Items.egg, new ItemStack(BirdItems.cooked_egg), 0.35F);
      GameRegistry.addSmelting(BirdItems.ground_beef, new ItemStack(BirdItems.burger), 0.35F);
      GameRegistry.addSmelting(Items.carrot, new ItemStack(BirdItems.cooked_carrot), 0.35F);
      GameRegistry.addSmelting(Items.apple, new ItemStack(BirdItems.baked_apple), 0.35F);
      GameRegistry.addSmelting(BirdItems.cold_chips, new ItemStack(BirdItems.hot_chips), 0.35F);
      GameRegistry.addSmelting(BirdItems.raw_crisps, new ItemStack(BirdItems.crisps), 0.35F);
      GameRegistry.addSmelting(BirdItems.raw_fish_sticks, new ItemStack(BirdItems.fish_sticks), 0.35F);
      GameRegistry.addSmelting(BirdItems.chocolate_bar, new ItemStack(BirdItems.hot_fudge), 0.35F);
      GameRegistry.addSmelting(Items.pumpkin_seeds, new ItemStack(BirdItems.roasted_pumpkin_seeds), 0.35F);
      GameRegistry.addSmelting(new ItemStack(Blocks.double_plant, 1, 0), new ItemStack(BirdItems.sunflower_seeds, 2), 0.35F);
      GameRegistry.addSmelting(BirdItems.raw_barbecue_chicken, new ItemStack(BirdItems.barbecue_chicken), 0.35F);
      GameRegistry.addSmelting(BirdItems.raw_barbecue_pork, new ItemStack(BirdItems.barbecue_pork), 0.35F);
      GameRegistry.addSmelting(BirdItems.sliced_cactus, new ItemStack(BirdItems.grilled_cactus), 0.35F);
      GameRegistry.addSmelting(Items.melon, new ItemStack(BirdItems.grilled_melon), 0.35F);
      GameRegistry.addSmelting(BirdItems.sliced_beets, new ItemStack(BirdItems.roast_beets), 0.35F);
      GameRegistry.addSmelting(BirdItems.ice_cream, new ItemStack(BirdItems.astronaut_ice_cream), 0.35F);
      GameRegistry.addSmelting(BirdItems.chocolate_milk, new ItemStack(BirdItems.hot_chocolate), 0.35F);
      GameRegistry.addSmelting(BirdItems.spiced_beef, new ItemStack(BirdItems.ancho_beef), 0.35F);
      GameRegistry.addSmelting(BirdItems.spiced_chicken, new ItemStack(BirdItems.ancho_chicken), 0.35F);
      GameRegistry.addSmelting(BirdItems.spiced_fish, new ItemStack(BirdItems.ancho_fish), 0.35F);
      GameRegistry.addSmelting(BirdItems.spiced_pork, new ItemStack(BirdItems.ancho_pork), 0.35F);
      GameRegistry.addSmelting(BirdItems.spiced_veggies, new ItemStack(BirdItems.ancho_veggies), 0.35F);
      GameRegistry.addSmelting(Items.reeds, new ItemStack(BirdItems.molasses), 0.35F);
      GameRegistry.addSmelting(Item.getItemFromBlock(Blocks.pumpkin), new ItemStack(BirdItems.grilled_pumpkin), 0.35F);
      GameRegistry.addSmelting(BirdItems.empty_sandwich, new ItemStack(BirdItems.toast), 0.35F);
      GameRegistry.addSmelting(BirdItems.cheese_sandwich, new ItemStack(BirdItems.t_cheese_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.egg_sandwich, new ItemStack(BirdItems.t_egg_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.bacon_sandwich, new ItemStack(BirdItems.t_bacon_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.bacon_and_cheese_sandwich, new ItemStack(BirdItems.t_bacon_and_cheese_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.egg_and_cheese_sandwich, new ItemStack(BirdItems.t_egg_and_cheese_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.bacon_and_egg_sandwich, new ItemStack(BirdItems.t_bacon_and_egg_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.bacon_egg_and_cheese_sandwich, new ItemStack(BirdItems.t_bacon_egg_and_cheese_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.pork_bbq_sandwich, new ItemStack(BirdItems.t_pork_bbq_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.chicken_bbq_sandwich, new ItemStack(BirdItems.t_chicken_bbq_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.hamburger, new ItemStack(BirdItems.t_hamburger), 0.35F);
      GameRegistry.addSmelting(BirdItems.bacon_hamburger, new ItemStack(BirdItems.t_bacon_hamburger), 0.35F);
      GameRegistry.addSmelting(BirdItems.cheeseburger, new ItemStack(BirdItems.t_cheeseburger), 0.35F);
      GameRegistry.addSmelting(BirdItems.bacon_cheeseburger, new ItemStack(BirdItems.t_bacon_cheeseburger), 0.35F);
      GameRegistry.addSmelting(BirdItems.steak_sandwich, new ItemStack(BirdItems.t_steak_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.cheesesteak, new ItemStack(BirdItems.t_cheesesteak), 0.35F);
      GameRegistry.addSmelting(BirdItems.veggie_hamburger, new ItemStack(BirdItems.t_veggie_hamburger), 0.35F);
      GameRegistry.addSmelting(BirdItems.veggie_cheeseburger, new ItemStack(BirdItems.t_veggie_cheeseburger), 0.35F);
      GameRegistry.addSmelting(BirdItems.veg_sandwich, new ItemStack(BirdItems.t_veg_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.cheesy_veg_sandwich, new ItemStack(BirdItems.t_cheesy_veg_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.cannibal_sandwich, new ItemStack(BirdItems.t_cannibal_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.real_cannibal_sandwich, new ItemStack(BirdItems.t_real_cannibal_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.chicken_sandwich, new ItemStack(BirdItems.t_chicken_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.cheesy_chicken_sandwich, new ItemStack(BirdItems.t_cheesy_chicken_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.buffalo_chicken_sandwich, new ItemStack(BirdItems.t_buffalo_chicken_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.cheesy_buffalo_chicken_sandwich, new ItemStack(BirdItems.t_cheesy_buffalo_chicken_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.ham_sandwich, new ItemStack(BirdItems.t_ham_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.ham_and_cheese_sandwich, new ItemStack(BirdItems.t_ham_and_cheese_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.egg_salad, new ItemStack(BirdItems.t_egg_salad), 0.35F);
      GameRegistry.addSmelting(BirdItems.fish_salad, new ItemStack(BirdItems.t_fish_salad), 0.35F);
      GameRegistry.addSmelting(BirdItems.chicken_salad, new ItemStack(BirdItems.t_chicken_salad), 0.35F);
      GameRegistry.addSmelting(BirdItems.chip_sandwich, new ItemStack(BirdItems.t_chip_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.cheesy_chip_sandwich, new ItemStack(BirdItems.t_cheesy_chip_sandwich), 0.35F);
      GameRegistry.addSmelting(BirdItems.cookie_dough, new ItemStack(Items.cookie, 8), 0.35F);
   }
}
