package com.nospace.birdsfoods.items;

import com.nospace.birdsfoods.items.BirdItems;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.OreDictionary;

public class BirdOreDict {

   public static void initDict() {
      OreDictionary.registerOre("listAllveggie", BirdItems.cooked_carrot);
      OreDictionary.registerOre("listAllveggie", Items.baked_potato);
      OreDictionary.registerOre("listAllveggie", Items.potato);
      OreDictionary.registerOre("listAllveggie", Items.carrot);
      OreDictionary.registerOre("listAllveggie", Blocks.red_mushroom);
      OreDictionary.registerOre("listAllveggie", Blocks.brown_mushroom);
      OreDictionary.registerOre("listAllveggie", BirdItems.roast_beets);
      OreDictionary.registerOre("listAllveggie", BirdItems.sliced_beets);
      OreDictionary.registerOre("listAllveggie", BirdItems.grilled_pumpkin);
      OreDictionary.registerOre("listAllgreenveggie", BirdItems.dandelion_salad);
      OreDictionary.registerOre("listAllfruit", Items.apple);
      OreDictionary.registerOre("listAllfruit", Items.melon);
      OreDictionary.registerOre("foodHalfmeat", BirdItems.burger);
      OreDictionary.registerOre("foodHalfmeat", BirdItems.bacon);
      OreDictionary.registerOre("foodHalfmeat", BirdItems.veggie_meat);
      OreDictionary.registerOre("foodHalfmeat", BirdItems.fish_fillet);
      OreDictionary.registerOre("foodHalfmeat", BirdItems.chopped_chicken);
      OreDictionary.registerOre("foodHalfmeat", BirdItems.chicken_fingers);
      OreDictionary.registerOre("foodHalfmeat", BirdItems.sliced_steak);
      OreDictionary.registerOre("foodHalfmeat", BirdItems.sliced_ham);
      OreDictionary.registerOre("foodHalfmeat", BirdItems.sliced_lamb);
      OreDictionary.registerOre("foodPizzameat", BirdItems.burger);
      OreDictionary.registerOre("foodPizzameat", BirdItems.bacon);
      OreDictionary.registerOre("foodPizzameat", BirdItems.veggie_meat);
      OreDictionary.registerOre("foodPizzameat", BirdItems.fish_fillet);
      OreDictionary.registerOre("foodPizzameat", BirdItems.chopped_chicken);
      OreDictionary.registerOre("foodPizzameat", BirdItems.chicken_fingers);
      OreDictionary.registerOre("foodPizzameat", BirdItems.barbecue_pork);
      OreDictionary.registerOre("foodPizzameat", BirdItems.barbecue_chicken);
      OreDictionary.registerOre("foodPizzameat", BirdItems.buffalo_chicken);
      OreDictionary.registerOre("foodPizzameat", BirdItems.sliced_steak);
      OreDictionary.registerOre("foodPizzameat", BirdItems.sliced_ham);
      OreDictionary.registerOre("foodPizzameat", BirdItems.sliced_lamb);
      OreDictionary.registerOre("foodPizzameat", BirdItems.ancho_beef);
      OreDictionary.registerOre("foodPizzameat", BirdItems.ancho_chicken);
      OreDictionary.registerOre("foodPizzameat", BirdItems.ancho_fish);
      OreDictionary.registerOre("foodPizzameat", BirdItems.ancho_pork);
      OreDictionary.registerOre("foodPizzameat", BirdItems.ancho_veggies);
      OreDictionary.registerOre("foodMeat", Items.cooked_beef);
      OreDictionary.registerOre("foodMeat", Items.cooked_chicken);
      OreDictionary.registerOre("foodMeat", new ItemStack(Items.cooked_fished, 1, 32767));
      OreDictionary.registerOre("foodMeat", Items.cooked_porkchop);
      OreDictionary.registerOre("Bacon", BirdItems.bacon);
      OreDictionary.registerOre("egg", Items.egg);
      OreDictionary.registerOre("listAllflower", new ItemStack(Blocks.yellow_flower, 1, 32767));
      OreDictionary.registerOre("listAllflower", new ItemStack(Blocks.red_flower, 1, 32767));
      OreDictionary.registerOre("listAllflower", new ItemStack(Blocks.double_plant, 1, 32767));
      OreDictionary.registerOre("listAllfishcooked", new ItemStack(Items.cooked_fished, 1, 32767));
      OreDictionary.registerOre("foodSalad", BirdItems.dandelion_salad);
      OreDictionary.registerOre("cropLettuce", BirdItems.dandelion_salad);
      OreDictionary.registerOre("cropSunflower", BirdItems.sunflower_seeds);
      OreDictionary.registerOre("foodNoodles", BirdItems.buckwheat_noodles);
      OreDictionary.registerOre("foodMashedpotato", BirdItems.mashed_potato);
      OreDictionary.registerOre("foodPasta", BirdItems.pasta);
      OreDictionary.registerOre("foodBacon", BirdItems.bacon);
      OreDictionary.registerOre("foodSyrup", BirdItems.molasses);
      OreDictionary.registerOre("foodButter", BirdItems.butter);
      OreDictionary.registerOre("foodGravy", BirdItems.gravy);
      OreDictionary.registerOre("foodToast", BirdItems.toast);
      OreDictionary.registerOre("foodYogurt", BirdItems.yogurt);
      OreDictionary.registerOre("foodMayo", BirdItems.yogurt);
      OreDictionary.registerOre("foodJam", BirdItems.jam);
      OreDictionary.registerOre("foodCheese", BirdItems.cheese);
      OreDictionary.registerOre("foodFries", BirdItems.hot_chips);
      OreDictionary.registerOre("foodCrisps", BirdItems.crisps);
      OreDictionary.registerOre("foodChips", BirdItems.crisps);
      OreDictionary.registerOre("foodFriedegg", BirdItems.cooked_egg);
      OreDictionary.registerOre("foodBoiledegg", BirdItems.cooked_egg);
      OreDictionary.registerOre("foodScrambledegg", BirdItems.cooked_egg);
      OreDictionary.registerOre("foodCookie", BirdItems.shortbread_cookie);
      OreDictionary.registerOre("foodCookie", Items.cookie);
      OreDictionary.registerOre("foodApplejuice", BirdItems.apple_juice);
      OreDictionary.registerOre("foodCarrotjuice", BirdItems.carrot_juice);
      OreDictionary.registerOre("foodMelonjuice", BirdItems.melon_juice);
      OreDictionary.registerOre("foodCactusjuice", BirdItems.cactus_juice);
      OreDictionary.registerOre("foodBeetjuice", BirdItems.beet_juice);
      OreDictionary.registerOre("listAlljuice", BirdItems.apple_juice);
      OreDictionary.registerOre("listAlljuice", BirdItems.carrot_juice);
      OreDictionary.registerOre("listAlljuice", BirdItems.melon_juice);
      OreDictionary.registerOre("listAlljuice", BirdItems.cactus_juice);
      OreDictionary.registerOre("listAlljuice", BirdItems.beet_juice);
      OreDictionary.registerOre("listAllmilk", BirdItems.bottle_of_milk);
      OreDictionary.registerOre("listAllmilk", Items.milk_bucket);
      OreDictionary.registerOre("listAllmushroom", Blocks.red_mushroom);
      OreDictionary.registerOre("listAllmushroom", Blocks.brown_mushroom);
      OreDictionary.registerOre("cropPumpkin", Blocks.pumpkin);
      OreDictionary.registerOre("cropMelon", Items.melon);
      OreDictionary.registerOre("cropWheat", Items.wheat);
      OreDictionary.registerOre("foodApplecider", BirdItems.apple_cider);
      OreDictionary.registerOre("foodCider", BirdItems.apple_cider);
      OreDictionary.registerOre("foodWine", BirdItems.melon_wine);
      OreDictionary.registerOre("foodWine", BirdItems.umeshu);
      OreDictionary.registerOre("foodBeer", BirdItems.beer);
      OreDictionary.registerOre("foodLiquor", BirdItems.beet_liquor);
      OreDictionary.registerOre("foodLiquer", BirdItems.beet_liquor);
      OreDictionary.registerOre("foodVodka", BirdItems.vodka);
      OreDictionary.registerOre("foodTequila", BirdItems.tequila);
      OreDictionary.registerOre("foodRum", BirdItems.rum);
      OreDictionary.registerOre("foodChocolatebar", BirdItems.chocolate_bar);
      OreDictionary.registerOre("foodIcecream", BirdItems.ice_cream);
      OreDictionary.registerOre("foodHotfudge", BirdItems.hot_fudge);
      OreDictionary.registerOre("foodChocolatesauce", BirdItems.hot_fudge);
      OreDictionary.registerOre("foodApplepie", BirdItems.apple_pie);
      OreDictionary.registerOre("cropApple", Items.apple);
      OreDictionary.registerOre("cropCarrot", Items.carrot);
      OreDictionary.registerOre("foodTortilla", BirdItems.empty_taco);
      OreDictionary.registerOre("listAllseed", BirdItems.sunflower_seeds);
      OreDictionary.registerOre("listAllseed", BirdItems.roasted_pumpkin_seeds);
      OreDictionary.registerOre("listAllseed", Items.wheat_seeds);
      OreDictionary.registerOre("listAllseed", Items.pumpkin_seeds);
      OreDictionary.registerOre("listAllseed", Items.melon_seeds);
      OreDictionary.registerOre("listAllwater", Items.water_bucket);
   }
}
