package com.nospace.birdsfoods.items;

import com.nospace.birdsfoods.items.BirdDrink;
import com.nospace.birdsfoods.items.BirdFood;
import com.nospace.birdsfoods.items.BirdSoup;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.GameRegistry.ObjectHolder;
import net.minecraft.item.Item;
import net.minecraft.potion.PotionEffect;

@ObjectHolder("birdsfoods")
public class BirdItems {

   public static BirdFood yogurt;
   public static BirdFood cheese;
   public static BirdFood cooked_egg;
   public static BirdDrink gravy;
   public static BirdFood fish_and_chips;
   public static BirdFood sunflower_seeds;
   public static BirdFood roasted_pumpkin_seeds;
   public static BirdFood fugu;
   public static BirdFood sashimi;
   public static BirdFood molasses;
   public static BirdFood butter;
   public static BirdFood jam;
   public static BirdFood stuffed_potato;
   public static BirdFood smothered_potato;
   public static BirdFood raw_crisps;
   public static BirdFood crisps;
   public static BirdFood beef_jerky;
   public static BirdFood cold_chips;
   public static BirdFood hot_chips;
   public static BirdFood mashed_potato;
   public static BirdFood mashed_potato_gravy;
   public static BirdFood cheese_fries;
   public static BirdFood chili_fries;
   public static BirdFood chili_cheese_fries;
   public static BirdFood poutine;
   public static BirdFood hotcakes;
   public static BirdFood hotcakes_with_syrup;
   public static BirdFood choc_hotcakes;
   public static BirdFood choc_hotcakes_syrup;
   public static BirdFood berry_hotcakes;
   public static BirdFood berry_hotcakes_syrup;
   public static BirdFood bacon_pancakes;
   public static BirdFood bacon_pancakes_syrup;
   public static BirdFood waffles;
   public static BirdFood waffles_syrup;
   public static BirdFood choc_waffles;
   public static BirdFood choc_waffles_syrup;
   public static BirdFood berry_waffles;
   public static BirdFood berry_waffles_syrup;
   public static BirdFood dandelion_salad;
   public static BirdFood spring_salad;
   public static BirdFood cobb_salad;
   public static BirdFood fruit_salad;
   public static BirdFood potato_salad;
   public static BirdFood grilled_melon;
   public static BirdFood sliced_cactus;
   public static BirdFood grilled_cactus;
   public static BirdFood grilled_pumpkin;
   public static BirdFood sliced_beets;
   public static BirdFood roast_beets;
   public static BirdFood candied_beets;
   public static BirdFood cooked_carrot;
   public static BirdFood baked_apple;
   public static BirdFood rabbit_pie;
   public static BirdFood chicken_pot_pie;
   public static BirdFood shepherds_pie;
   public static BirdFood fish_pie;
   public static BirdFood cottage_pie;
   public static BirdFood veg_pie;
   public static BirdFood quiche;
   public static BirdFood mushroom_quiche;
   public static BirdFood bacon_quiche;
   public static BirdFood fish_quiche;
   public static BirdFood green_quiche;
   public static BirdSoup beef_stew;
   public static BirdSoup veg_stew;
   public static BirdSoup pumpkin_soup;
   public static BirdSoup potato_soup;
   public static BirdSoup chicken_noodle_soup;
   public static BirdSoup chili;
   public static BirdSoup hot_chili;
   public static BirdFood pizza;
   public static BirdFood meat_pizza;
   public static BirdFood veg_pizza;
   public static BirdFood pizza_supreme;
   public static BirdFood raw_bacon;
   public static BirdFood bacon;
   public static BirdFood sliced_lamb;
   public static BirdFood chopped_chicken;
   public static BirdFood raw_fingers;
   public static BirdFood chicken_fingers;
   public static BirdFood raw_barbecue_pork;
   public static BirdFood barbecue_pork;
   public static BirdFood raw_barbecue_chicken;
   public static BirdFood barbecue_chicken;
   public static BirdFood ground_beef;
   public static BirdFood burger;
   public static BirdFood sliced_steak;
   public static BirdFood veggie_meat;
   public static BirdFood raw_fish_sticks;
   public static BirdFood fish_sticks;
   public static BirdFood fish_fillet;
   public static BirdFood buffalo_chicken;
   public static BirdFood sliced_ham;
   public static BirdFood empty_sandwich;
   public static BirdFood toast;
   public static BirdFood buttered_toast;
   public static BirdFood jammy_toast;
   public static BirdFood jammy_buttered_toast;
   public static BirdFood pita;
   public static BirdFood chicken_salad;
   public static BirdFood t_chicken_salad;
   public static BirdFood egg_salad;
   public static BirdFood t_egg_salad;
   public static BirdFood fish_salad;
   public static BirdFood t_fish_salad;
   public static BirdFood cheese_sandwich;
   public static BirdFood t_cheese_sandwich;
   public static BirdFood egg_sandwich;
   public static BirdFood t_egg_sandwich;
   public static BirdFood bacon_sandwich;
   public static BirdFood t_bacon_sandwich;
   public static BirdFood bacon_and_cheese_sandwich;
   public static BirdFood t_bacon_and_cheese_sandwich;
   public static BirdFood egg_and_cheese_sandwich;
   public static BirdFood t_egg_and_cheese_sandwich;
   public static BirdFood bacon_and_egg_sandwich;
   public static BirdFood t_bacon_and_egg_sandwich;
   public static BirdFood bacon_egg_and_cheese_sandwich;
   public static BirdFood t_bacon_egg_and_cheese_sandwich;
   public static BirdFood pork_bbq_sandwich;
   public static BirdFood t_pork_bbq_sandwich;
   public static BirdFood chicken_bbq_sandwich;
   public static BirdFood t_chicken_bbq_sandwich;
   public static BirdFood hamburger;
   public static BirdFood t_hamburger;
   public static BirdFood bacon_hamburger;
   public static BirdFood t_bacon_hamburger;
   public static BirdFood cheeseburger;
   public static BirdFood t_cheeseburger;
   public static BirdFood bacon_cheeseburger;
   public static BirdFood t_bacon_cheeseburger;
   public static BirdFood steak_sandwich;
   public static BirdFood t_steak_sandwich;
   public static BirdFood cheesesteak;
   public static BirdFood t_cheesesteak;
   public static BirdFood veggie_hamburger;
   public static BirdFood t_veggie_hamburger;
   public static BirdFood veggie_cheeseburger;
   public static BirdFood t_veggie_cheeseburger;
   public static BirdFood veg_sandwich;
   public static BirdFood t_veg_sandwich;
   public static BirdFood cheesy_veg_sandwich;
   public static BirdFood t_cheesy_veg_sandwich;
   public static BirdFood gyro;
   public static BirdFood veggie_gyro;
   public static BirdFood dagwood;
   public static BirdFood cannibal_sandwich;
   public static BirdFood t_cannibal_sandwich;
   public static BirdFood real_cannibal_sandwich;
   public static BirdFood t_real_cannibal_sandwich;
   public static BirdFood chicken_sandwich;
   public static BirdFood t_chicken_sandwich;
   public static BirdFood cheesy_chicken_sandwich;
   public static BirdFood t_cheesy_chicken_sandwich;
   public static BirdFood buffalo_chicken_sandwich;
   public static BirdFood t_buffalo_chicken_sandwich;
   public static BirdFood cheesy_buffalo_chicken_sandwich;
   public static BirdFood t_cheesy_buffalo_chicken_sandwich;
   public static BirdFood ham_sandwich;
   public static BirdFood t_ham_sandwich;
   public static BirdFood ham_and_cheese_sandwich;
   public static BirdFood t_ham_and_cheese_sandwich;
   public static BirdFood chip_sandwich;
   public static BirdFood t_chip_sandwich;
   public static BirdFood cheesy_chip_sandwich;
   public static BirdFood t_cheesy_chip_sandwich;
   public static BirdFood bacone;
   public static BirdFood buckwheat_noodles;
   public static BirdFood beef_soba;
   public static BirdFood chicken_soba;
   public static BirdFood fish_soba;
   public static BirdFood veggie_soba;
   public static BirdFood pasta;
   public static BirdFood cincinnati_chili;
   public static BirdFood mac_and_cheese;
   public static BirdFood alfredo_sauce;
   public static BirdFood fettucine_alfredo;
   public static BirdFood chicken_alfredo;
   public static BirdFood seafood_alfredo;
   public static BirdFood mushroom_alfredo;
   public static BirdFood squid_ink_pasta;
   public static BirdFood curry_sauce;
   public static BirdFood beef_vindaloo;
   public static BirdFood lamb_vindaloo;
   public static BirdFood chicken_tikka;
   public static BirdFood paneer_tikka;
   public static BirdFood pork_curry;
   public static BirdFood fish_curry;
   public static BirdFood veg_curry;
   public static BirdFood pumpkin_curry;
   public static BirdDrink apple_juice;
   public static BirdDrink carrot_juice;
   public static BirdDrink melon_juice;
   public static BirdDrink beet_juice;
   public static BirdDrink cactus_juice;
   public static BirdDrink bottle_of_milk;
   public static BirdDrink herbal_tea;
   public static BirdDrink sweet_tea;
   public static BirdDrink milk_tea;
   public static BirdDrink sweet_milk_tea;
   public static BirdDrink iced_tea;
   public static BirdDrink sweet_iced_tea;
   public static BirdDrink chocolate_milk;
   public static BirdDrink hot_chocolate;
   public static BirdDrink apple_cider;
   public static BirdDrink melon_wine;
   public static BirdDrink beer;
   public static BirdDrink beet_liquor;
   public static BirdDrink vodka;
   public static BirdDrink poitin;
   public static BirdDrink tequila;
   public static BirdDrink rum;
   public static BirdDrink umeshu;
   public static BirdDrink scumble;
   public static BirdFood empty_taco;
   public static BirdFood spiced_beef;
   public static BirdFood spiced_chicken;
   public static BirdFood spiced_fish;
   public static BirdFood spiced_pork;
   public static BirdFood spiced_veggies;
   public static BirdFood ancho_beef;
   public static BirdFood ancho_chicken;
   public static BirdFood ancho_fish;
   public static BirdFood ancho_pork;
   public static BirdFood ancho_veggies;
   public static BirdFood beef_taco;
   public static BirdFood chicken_taco;
   public static BirdFood fish_taco;
   public static BirdFood pork_taco;
   public static BirdFood veggie_taco;
   public static BirdFood cheesy_beef_taco;
   public static BirdFood cheesy_chicken_taco;
   public static BirdFood cheesy_pork_taco;
   public static BirdFood cheesy_fish_taco;
   public static BirdFood cheesy_veggie_taco;
   public static BirdFood beef_taco_with_cream;
   public static BirdFood chicken_taco_with_cream;
   public static BirdFood pork_taco_with_cream;
   public static BirdFood fish_taco_with_cream;
   public static BirdFood veggie_taco_with_cream;
   public static BirdFood beef_taco_with_greens;
   public static BirdFood chicken_taco_with_greens;
   public static BirdFood pork_taco_with_greens;
   public static BirdFood fish_taco_with_greens;
   public static BirdFood veggie_taco_with_greens;
   public static BirdFood cheesy_beef_taco_with_cream;
   public static BirdFood cheesy_chicken_taco_with_cream;
   public static BirdFood cheesy_pork_taco_with_cream;
   public static BirdFood cheesy_fish_taco_with_cream;
   public static BirdFood cheesy_veggie_taco_with_cream;
   public static BirdFood cheesy_beef_taco_with_greens;
   public static BirdFood cheesy_chicken_taco_with_greens;
   public static BirdFood cheesy_pork_taco_with_greens;
   public static BirdFood cheesy_fish_taco_with_greens;
   public static BirdFood cheesy_veggie_taco_with_greens;
   public static BirdFood beef_taco_with_cream_and_greens;
   public static BirdFood chicken_taco_with_cream_and_greens;
   public static BirdFood pork_taco_with_cream_and_greens;
   public static BirdFood fish_taco_with_cream_and_greens;
   public static BirdFood veggie_taco_with_cream_and_greens;
   public static BirdFood beef_taco_supreme;
   public static BirdFood chicken_taco_supreme;
   public static BirdFood pork_taco_supreme;
   public static BirdFood fish_taco_supreme;
   public static BirdFood veggie_taco_supreme;
   public static BirdFood breakfast_burrito;
   public static BirdFood taako;
   public static BirdFood chocolate_bar;
   public static BirdFood ice_cream;
   public static BirdFood hot_fudge;
   public static BirdFood ice_cream_sundae;
   public static BirdFood apple_pie;
   public static BirdFood apple_pie_a_la_mode;
   public static BirdFood astronaut_ice_cream;
   public static BirdFood plum_pudding;
   public static BirdDrink pumpkin_spice_latte;
   public static BirdFood pumpkin_bread;
   public static BirdFood shortbread_cookie;
   public static BirdFood cookie_dough;
   public static BirdFood ice_cream_bacone;


   private static void initItems() {
      raw_fingers.isRaw().setPotionEffect(new PotionEffect(17, 300, 0), 0.3F);
      raw_barbecue_chicken.isRaw().setPotionEffect(new PotionEffect(17, 300, 0), 0.3F);
      fugu.isDangerous();
      rabbit_pie.isQuality();
      chicken_pot_pie.isQuality();
      shepherds_pie.isQuality();
      cottage_pie.isQuality();
      fish_pie.isQuality();
      veg_pie.isQuality();
      bacon_cheeseburger.isQuality();
      t_bacon_cheeseburger.isQuality();
      veggie_cheeseburger.isQuality();
      t_veggie_cheeseburger.isQuality();
      real_cannibal_sandwich.isRaw().setPotionEffect(new PotionEffect(17, 300, 0), 0.2F);
      t_real_cannibal_sandwich.isRaw().setPotionEffect(new PotionEffect(17, 300, 0), 0.1F);
      cookie_dough.isRaw().setPotionEffect(new PotionEffect(17, 300, 0), 0.1F);
      dagwood.isDagwood();
      mushroom_alfredo.isQuality();
      chicken_alfredo.isQuality();
      seafood_alfredo.isQuality();
      beef_taco_supreme.isQuality();
      chicken_taco_supreme.isQuality();
      pork_taco_supreme.isQuality();
      fish_taco_supreme.isQuality();
      veggie_taco_supreme.isQuality();
      veg_pizza.isQuality();
      meat_pizza.isQuality();
      pizza_supreme.isQuality();
      bacone.isQuality();
      ice_cream_bacone.isQuality();
      bacon_pancakes_syrup.isQuality();
      taako.isPalliative().isTaako();
      chicken_noodle_soup.isPalliative();
      chocolate_bar.isPalliative();
      ice_cream.isPalliative();
      ice_cream_sundae.isPalliative();
      apple_pie.isQuality();
      hot_chili.isChili();
      apple_pie_a_la_mode.isQuality().isPalliative();
      bottle_of_milk.isPalliative().setAlwaysEdible();
      herbal_tea.isPalliative().setAlwaysEdible();
      iced_tea.isPalliative().setAlwaysEdible();
      sweet_iced_tea.isPalliative().setAlwaysEdible();
      sweet_tea.isPalliative().setAlwaysEdible();
      milk_tea.isPalliative().setAlwaysEdible();
      sweet_milk_tea.isPalliative().setAlwaysEdible();
      chocolate_milk.isPalliative().setAlwaysEdible();
      hot_chocolate.isPalliative().setAlwaysEdible();
      pumpkin_spice_latte.isPalliative().setAlwaysEdible();
      apple_cider.isAlcoholic(0.05F, 0.2F, 0.4F).isCider().setAlwaysEdible();
      melon_wine.isAlcoholic(0.05F, 0.2F, 0.4F).isWine().setAlwaysEdible();
      beer.isAlcoholic(0.05F, 0.2F, 0.4F).isBeer().setAlwaysEdible();
      beet_liquor.isAlcoholic(0.05F, 0.2F, 0.4F).isLiquor().setAlwaysEdible();
      vodka.isAlcoholic(0.05F, 0.2F, 0.4F).isVodka().setAlwaysEdible();
      poitin.isAlcoholic(0.05F, 0.2F, 0.4F).isPoitin().setAlwaysEdible();
      tequila.isAlcoholic(1.0F, 1.0F, 1.0F).isTequila().setAlwaysEdible();
      rum.isAlcoholic(0.05F, 0.2F, 0.4F).isRum().setAlwaysEdible();
      umeshu.isAlcoholic(0.05F, 0.2F, 0.4F).isUmeshu().setAlwaysEdible();
      scumble.isAlcoholic(0.2F, 0.5F, 0.7F).isScumble().setAlwaysEdible();
   }

   public static final void init() {
      GameRegistry.registerItem(yogurt = new BirdFood(2, 0.3F, false, "yogurt"), "yogurt");
      GameRegistry.registerItem(cheese = new BirdFood(2, 0.4F, true, "cheese"), "cheese");
      GameRegistry.registerItem(cooked_egg = new BirdFood(3, 0.3F, true, "cooked_egg"), "cooked_egg");
      GameRegistry.registerItem(gravy = new BirdDrink(4, 0.6F, false, "gravy"), "gravy");
      GameRegistry.registerItem(fish_and_chips = new BirdFood(10, 0.6F, false, "fish_and_chips"), "fish_and_chips");
      GameRegistry.registerItem(sunflower_seeds = new BirdFood(2, 0.2F, false, "sunflower_seeds"), "sunflower_seeds");
      GameRegistry.registerItem(roasted_pumpkin_seeds = new BirdFood(2, 0.2F, false, "roasted_pumpkin_seeds"), "roasted_pumpkin_seeds");
      GameRegistry.registerItem(fugu = new BirdFood(1, 2.0F, false, "fugu"), "fugu");
      GameRegistry.registerItem(sashimi = new BirdFood(1, 1.0F, false, "sashimi"), "sashimi");
      GameRegistry.registerItem(molasses = new BirdFood(2, 0.2F, false, "molasses"), "molasses");
      GameRegistry.registerItem(butter = new BirdFood(1, 0.2F, false, "butter"), "butter");
      GameRegistry.registerItem(jam = new BirdFood(3, 0.4F, false, "jam"), "jam");
      GameRegistry.registerItem(stuffed_potato = new BirdFood(12, 1.0F, false, "stuffed_potato"), "stuffed_potato");
      GameRegistry.registerItem(smothered_potato = new BirdFood(12, 1.0F, false, "smothered_potato"), "smothered_potato");
      GameRegistry.registerItem(raw_crisps = new BirdFood(1, 0.2F, false, "raw_crisps"), "raw_crisps");
      GameRegistry.registerItem(crisps = new BirdFood(3, 0.7F, false, "crisps"), "crisps");
      GameRegistry.registerItem(beef_jerky = new BirdFood(3, 0.1F, true, "beef_jerky"), "beef_jerky");
      GameRegistry.registerItem(cold_chips = new BirdFood(1, 0.2F, false, "cold_chips"), "cold_chips");
      GameRegistry.registerItem(hot_chips = new BirdFood(4, 0.7F, false, "hot_chips"), "hot_chips");
      GameRegistry.registerItem(mashed_potato = new BirdFood(6, 0.7F, false, "mashed_potato"), "mashed_potato");
      GameRegistry.registerItem(mashed_potato_gravy = new BirdFood(10, 0.8F, false, "mashed_potato_gravy"), "mashed_potato_gravy");
      GameRegistry.registerItem(cheese_fries = new BirdFood(6, 0.8F, false, "cheese_fries"), "cheese_fries");
      GameRegistry.registerItem(chili_fries = new BirdFood(10, 0.8F, false, "chili_fries"), "chili_fries");
      GameRegistry.registerItem(chili_cheese_fries = new BirdFood(12, 0.8F, false, "chili_cheese_fries"), "chili_cheese_fries");
      GameRegistry.registerItem(poutine = new BirdFood(10, 0.9F, false, "poutine"), "poutine");
      GameRegistry.registerItem(hotcakes = new BirdFood(5, 0.6F, false, "hotcakes"), "hotcakes");
      GameRegistry.registerItem(hotcakes_with_syrup = new BirdFood(7, 0.9F, false, "hotcakes_with_syrup"), "hotcakes_with_syrup");
      GameRegistry.registerItem(choc_hotcakes = new BirdFood(6, 0.6F, false, "choc_hotcakes"), "choc_hotcakes");
      GameRegistry.registerItem(choc_hotcakes_syrup = new BirdFood(8, 0.9F, false, "choc_hotcakes_syrup"), "choc_hotcakes_syrup");
      GameRegistry.registerItem(berry_hotcakes = new BirdFood(7, 0.8F, false, "berry_hotcakes"), "berry_hotcakes");
      GameRegistry.registerItem(berry_hotcakes_syrup = new BirdFood(9, 1.1F, false, "berry_hotcakes_syrup"), "berry_hotcakes_syrup");
      GameRegistry.registerItem(bacon_pancakes = new BirdFood(9, 0.8F, false, "bacon_pancakes"), "bacon_pancakes");
      GameRegistry.registerItem(bacon_pancakes_syrup = new BirdFood(10, 0.9F, false, "bacon_pancakes_syrup"), "bacon_pancakes_syrup");
      GameRegistry.registerItem(waffles = new BirdFood(5, 0.7F, false, "waffles"), "waffles");
      GameRegistry.registerItem(waffles_syrup = new BirdFood(7, 1.0F, false, "waffles_syrup"), "waffles_syrup");
      GameRegistry.registerItem(choc_waffles = new BirdFood(6, 0.7F, false, "choc_waffles"), "choc_waffles");
      GameRegistry.registerItem(choc_waffles_syrup = new BirdFood(8, 1.0F, false, "choc_waffles_syrup"), "choc_waffles_syrup");
      GameRegistry.registerItem(berry_waffles = new BirdFood(7, 0.9F, false, "berry_waffles"), "berry_waffles");
      GameRegistry.registerItem(berry_waffles_syrup = new BirdFood(9, 1.2F, false, "berry_waffles_syrup"), "berry_waffles_syrup");
      GameRegistry.registerItem(dandelion_salad = new BirdFood(4, 0.3F, false, "dandelion_salad"), "dandelion_salad");
      GameRegistry.registerItem(spring_salad = new BirdFood(8, 0.6F, false, "spring_salad"), "spring_salad");
      GameRegistry.registerItem(cobb_salad = new BirdFood(10, 0.9F, false, "cobb_salad"), "cobb_salad");
      GameRegistry.registerItem(fruit_salad = new BirdFood(6, 0.5F, false, "fruit_salad"), "fruit_salad");
      GameRegistry.registerItem(potato_salad = new BirdFood(6, 0.8F, false, "potato_salad"), "potato_salad");
      GameRegistry.registerItem(grilled_melon = new BirdFood(4, 0.4F, false, "grilled_melon"), "grilled_melon");
      GameRegistry.registerItem(sliced_cactus = new BirdFood(2, 0.3F, false, "sliced_cactus"), "sliced_cactus");
      GameRegistry.registerItem(grilled_cactus = new BirdFood(2, 0.5F, false, "grilled_cactus"), "grilled_cactus");
      GameRegistry.registerItem(grilled_pumpkin = new BirdFood(4, 0.5F, false, "grilled_pumpkin"), "grilled_pumpkin");
      GameRegistry.registerItem(sliced_beets = new BirdFood(1, 0.2F, false, "sliced_beets"), "sliced_beets");
      GameRegistry.registerItem(roast_beets = new BirdFood(2, 0.8F, false, "roast_beets"), "roast_beets");
      GameRegistry.registerItem(candied_beets = new BirdFood(4, 0.8F, false, "candied_beets"), "candied_beets");
      GameRegistry.registerItem(cooked_carrot = new BirdFood(4, 0.6F, false, "cooked_carrot"), "cooked_carrot");
      GameRegistry.registerItem(baked_apple = new BirdFood(5, 0.5F, false, "baked_apple"), "baked_apple");
      GameRegistry.registerItem(rabbit_pie = new BirdFood(14, 0.8F, false, "rabbit_pie"), "rabbit_pie");
      GameRegistry.registerItem(chicken_pot_pie = new BirdFood(14, 0.8F, false, "chicken_pot_pie"), "chicken_pot_pie");
      GameRegistry.registerItem(shepherds_pie = new BirdFood(14, 0.8F, false, "shepherds_pie"), "shepherds_pie");
      GameRegistry.registerItem(fish_pie = new BirdFood(14, 0.8F, false, "fish_pie"), "fish_pie");
      GameRegistry.registerItem(cottage_pie = new BirdFood(14, 0.8F, false, "cottage_pie"), "cottage_pie");
      GameRegistry.registerItem(veg_pie = new BirdFood(14, 0.8F, false, "veg_pie"), "veg_pie");
      GameRegistry.registerItem(quiche = new BirdFood(8, 1.0F, false, "quiche"), "quiche");
      GameRegistry.registerItem(mushroom_quiche = new BirdFood(10, 1.0F, false, "mushroom_quiche"), "mushroom_quiche");
      GameRegistry.registerItem(bacon_quiche = new BirdFood(12, 1.0F, false, "bacon_quiche"), "bacon_quiche");
      GameRegistry.registerItem(fish_quiche = new BirdFood(11, 1.0F, false, "fish_quiche"), "fish_quiche");
      GameRegistry.registerItem(green_quiche = new BirdFood(12, 1.0F, false, "green_quiche"), "green_quiche");
      GameRegistry.registerItem(beef_stew = new BirdSoup(14, "beef_stew"), "beef_stew");
      GameRegistry.registerItem(veg_stew = new BirdSoup(12, "veg_stew"), "veg_stew");
      GameRegistry.registerItem(pumpkin_soup = new BirdSoup(9, "pumpkin_soup"), "pumpkin_soup");
      GameRegistry.registerItem(potato_soup = new BirdSoup(9, "potato_soup"), "potato_soup");
      GameRegistry.registerItem(chicken_noodle_soup = new BirdSoup(12, "chicken_noodle_soup"), "chicken_noodle_soup");
      GameRegistry.registerItem(chili = new BirdSoup(7, "chili"), "chili");
      GameRegistry.registerItem(hot_chili = new BirdSoup(9, "hot_chili"), "hot_chili");
      GameRegistry.registerItem(pizza = new BirdFood(9, 0.8F, false, "pizza"), "pizza");
      GameRegistry.registerItem(meat_pizza = new BirdFood(15, 0.8F, false, "meat_pizza"), "meat_pizza");
      GameRegistry.registerItem(veg_pizza = new BirdFood(14, 0.8F, false, "veg_pizza"), "veg_pizza");
      GameRegistry.registerItem(pizza_supreme = new BirdFood(20, 1.0F, false, "pizza_supreme"), "pizza_supreme");
      GameRegistry.registerItem(raw_bacon = new BirdFood(2, 0.2F, true, "raw_bacon"), "raw_bacon");
      GameRegistry.registerItem(bacon = new BirdFood(4, 0.8F, true, "bacon"), "bacon");
      GameRegistry.registerItem(sliced_lamb = new BirdFood(3, 0.8F, true, "sliced_lamb"), "sliced_lamb");
      GameRegistry.registerItem(chopped_chicken = new BirdFood(3, 0.6F, true, "chopped_chicken"), "chopped_chicken");
      GameRegistry.registerItem(raw_fingers = new BirdFood(2, 0.1F, true, "raw_fingers"), "raw_fingers");
      GameRegistry.registerItem(chicken_fingers = new BirdFood(3, 0.7F, true, "chicken_fingers"), "chicken_fingers");
      GameRegistry.registerItem(raw_barbecue_pork = new BirdFood(2, 0.2F, false, "raw_barbecue_pork"), "raw_barbecue_pork");
      GameRegistry.registerItem(barbecue_pork = new BirdFood(4, 1.0F, false, "barbecue_pork"), "barbecue_pork");
      GameRegistry.registerItem(raw_barbecue_chicken = new BirdFood(2, 0.1F, false, "raw_barbecue_chicken"), "raw_barbecue_chicken");
      GameRegistry.registerItem(barbecue_chicken = new BirdFood(3, 1.0F, false, "barbecue_chicken"), "barbecue_chicken");
      GameRegistry.registerItem(ground_beef = new BirdFood(2, 0.1F, true, "ground_beef"), "ground_beef");
      GameRegistry.registerItem(burger = new BirdFood(4, 0.8F, true, "burger"), "burger");
      GameRegistry.registerItem(sliced_steak = new BirdFood(4, 0.8F, true, "sliced_steak"), "sliced_steak");
      GameRegistry.registerItem(veggie_meat = new BirdFood(4, 0.9F, false, "veggie_meat"), "veggie_meat");
      GameRegistry.registerItem(raw_fish_sticks = new BirdFood(1, 0.1F, false, "raw_fish_sticks"), "raw_fish_sticks");
      GameRegistry.registerItem(fish_sticks = new BirdFood(3, 0.4F, false, "fish_sticks"), "fish_sticks");
      GameRegistry.registerItem(fish_fillet = new BirdFood(3, 0.6F, false, "fish_fillet"), "fish_fillet");
      GameRegistry.registerItem(buffalo_chicken = new BirdFood(4, 0.8F, false, "buffalo_chicken"), "buffalo_chicken");
      GameRegistry.registerItem(sliced_ham = new BirdFood(4, 0.8F, true, "sliced_ham"), "sliced_ham");
      GameRegistry.registerItem(empty_sandwich = new BirdFood(2, 0.6F, false, "empty_sandwich"), "empty_sandwich");
      GameRegistry.registerItem(toast = new BirdFood(2, 0.7F, false, "toast"), "toast");
      GameRegistry.registerItem(buttered_toast = new BirdFood(3, 0.8F, false, "buttered_toast"), "buttered_toast");
      GameRegistry.registerItem(jammy_toast = new BirdFood(5, 0.8F, false, "jammy_toast"), "jammy_toast");
      GameRegistry.registerItem(jammy_buttered_toast = new BirdFood(8, 0.8F, false, "jammy_buttered_toast"), "jammy_buttered_toast");
      GameRegistry.registerItem(pita = new BirdFood(3, 0.6F, false, "pita"), "pita");
      GameRegistry.registerItem(chicken_salad = new BirdFood(9, 0.8F, false, "chicken_salad"), "chicken_salad");
      GameRegistry.registerItem(t_chicken_salad = new BirdFood(11, 0.8F, false, "t_chicken_salad"), "t_chicken_salad");
      GameRegistry.registerItem(egg_salad = new BirdFood(7, 0.8F, false, "egg_salad"), "egg_salad");
      GameRegistry.registerItem(t_egg_salad = new BirdFood(9, 0.8F, false, "t_egg_salad"), "t_egg_salad");
      GameRegistry.registerItem(fish_salad = new BirdFood(9, 0.8F, false, "fish_salad"), "fish_salad");
      GameRegistry.registerItem(t_fish_salad = new BirdFood(11, 0.8F, false, "t_fish_salad"), "t_fish_salad");
      GameRegistry.registerItem(cheese_sandwich = new BirdFood(5, 0.6F, false, "cheese_sandwich"), "cheese_sandwich");
      GameRegistry.registerItem(t_cheese_sandwich = new BirdFood(7, 0.6F, false, "t_cheese_sandwich"), "t_cheese_sandwich");
      GameRegistry.registerItem(egg_sandwich = new BirdFood(5, 0.6F, false, "egg_sandwich"), "egg_sandwich");
      GameRegistry.registerItem(t_egg_sandwich = new BirdFood(7, 0.6F, false, "t_egg_sandwich"), "t_egg_sandwich");
      GameRegistry.registerItem(bacon_sandwich = new BirdFood(6, 0.8F, false, "bacon_sandwich"), "bacon_sandwich");
      GameRegistry.registerItem(t_bacon_sandwich = new BirdFood(8, 0.8F, false, "t_bacon_sandwich"), "t_bacon_sandwich");
      GameRegistry.registerItem(bacon_and_cheese_sandwich = new BirdFood(8, 0.8F, false, "bacon_and_cheese_sandwich"), "bacon_and_cheese_sandwich");
      GameRegistry.registerItem(t_bacon_and_cheese_sandwich = new BirdFood(10, 0.8F, false, "t_bacon_and_cheese_sandwich"), "t_bacon_and_cheese_sandwich");
      GameRegistry.registerItem(egg_and_cheese_sandwich = new BirdFood(8, 0.7F, false, "egg_and_cheese_sandwich"), "egg_and_cheese_sandwich");
      GameRegistry.registerItem(t_egg_and_cheese_sandwich = new BirdFood(10, 0.7F, false, "t_egg_and_cheese_sandwich"), "t_egg_and_cheese_sandwich");
      GameRegistry.registerItem(bacon_and_egg_sandwich = new BirdFood(8, 1.0F, false, "bacon_and_egg_sandwich"), "bacon_and_egg_sandwich");
      GameRegistry.registerItem(t_bacon_and_egg_sandwich = new BirdFood(10, 1.0F, false, "t_bacon_and_egg_sandwich"), "t_bacon_and_egg_sandwich");
      GameRegistry.registerItem(bacon_egg_and_cheese_sandwich = new BirdFood(10, 1.0F, false, "bacon_egg_and_cheese_sandwich"), "bacon_egg_and_cheese_sandwich");
      GameRegistry.registerItem(t_bacon_egg_and_cheese_sandwich = new BirdFood(12, 1.0F, false, "t_bacon_egg_and_cheese_sandwich"), "t_bacon_egg_and_cheese_sandwich");
      GameRegistry.registerItem(pork_bbq_sandwich = new BirdFood(6, 1.0F, false, "pork_bbq_sandwich"), "pork_bbq_sandwich");
      GameRegistry.registerItem(t_pork_bbq_sandwich = new BirdFood(8, 1.0F, false, "t_pork_bbq_sandwich"), "t_pork_bbq_sandwich");
      GameRegistry.registerItem(chicken_bbq_sandwich = new BirdFood(5, 1.0F, false, "chicken_bbq_sandwich"), "chicken_bbq_sandwich");
      GameRegistry.registerItem(t_chicken_bbq_sandwich = new BirdFood(7, 1.0F, false, "t_chicken_bbq_sandwich"), "t_chicken_bbq_sandwich");
      GameRegistry.registerItem(hamburger = new BirdFood(6, 0.8F, false, "hamburger"), "hamburger");
      GameRegistry.registerItem(t_hamburger = new BirdFood(8, 0.8F, false, "t_hamburger"), "t_hamburger");
      GameRegistry.registerItem(bacon_hamburger = new BirdFood(10, 1.0F, false, "bacon_hamburger"), "bacon_hamburger");
      GameRegistry.registerItem(t_bacon_hamburger = new BirdFood(12, 1.0F, false, "t_bacon_hamburger"), "t_bacon_hamburger");
      GameRegistry.registerItem(cheeseburger = new BirdFood(8, 1.0F, false, "cheeseburger"), "cheeseburger");
      GameRegistry.registerItem(t_cheeseburger = new BirdFood(10, 1.0F, false, "t_cheeseburger"), "t_cheeseburger");
      GameRegistry.registerItem(bacon_cheeseburger = new BirdFood(12, 1.2F, false, "bacon_cheeseburger"), "bacon_cheeseburger");
      GameRegistry.registerItem(t_bacon_cheeseburger = new BirdFood(14, 1.2F, false, "t_bacon_cheeseburger"), "t_bacon_cheeseburger");
      GameRegistry.registerItem(steak_sandwich = new BirdFood(6, 1.0F, false, "steak_sandwich"), "steak_sandwich");
      GameRegistry.registerItem(t_steak_sandwich = new BirdFood(8, 1.0F, false, "t_steak_sandwich"), "t_steak_sandwich");
      GameRegistry.registerItem(cheesesteak = new BirdFood(8, 1.0F, false, "cheesesteak"), "cheesesteak");
      GameRegistry.registerItem(t_cheesesteak = new BirdFood(10, 1.0F, false, "t_cheesesteak"), "t_cheesesteak");
      GameRegistry.registerItem(veggie_hamburger = new BirdFood(7, 0.9F, false, "veggie_hamburger"), "veggie_hamburger");
      GameRegistry.registerItem(t_veggie_hamburger = new BirdFood(9, 0.9F, false, "t_veggie_hamburger"), "t_veggie_hamburger");
      GameRegistry.registerItem(veggie_cheeseburger = new BirdFood(10, 1.0F, false, "veggie_cheeseburger"), "veggie_cheeseburger");
      GameRegistry.registerItem(t_veggie_cheeseburger = new BirdFood(12, 1.0F, false, "t_veggie_cheeseburger"), "t_veggie_cheeseburger");
      GameRegistry.registerItem(veg_sandwich = new BirdFood(8, 0.8F, false, "veg_sandwich"), "veg_sandwich");
      GameRegistry.registerItem(t_veg_sandwich = new BirdFood(10, 0.8F, false, "t_veg_sandwich"), "t_veg_sandwich");
      GameRegistry.registerItem(cheesy_veg_sandwich = new BirdFood(10, 1.0F, false, "cheesy_veg_sandwich"), "cheesy_veg_sandwich");
      GameRegistry.registerItem(t_cheesy_veg_sandwich = new BirdFood(12, 1.0F, false, "t_cheesy_veg_sandwich"), "t_cheesy_veg_sandwich");
      GameRegistry.registerItem(gyro = new BirdFood(10, 0.9F, false, "gyro"), "gyro");
      GameRegistry.registerItem(veggie_gyro = new BirdFood(10, 0.9F, false, "veggie_gyro"), "veggie_gyro");
      GameRegistry.registerItem(dagwood = new BirdFood(20, 1.0F, false, "dagwood"), "dagwood");
      GameRegistry.registerItem(cannibal_sandwich = new BirdFood(5, 0.8F, false, "cannibal_sandwich"), "cannibal_sandwich");
      GameRegistry.registerItem(t_cannibal_sandwich = new BirdFood(7, 0.8F, false, "t_cannibal_sandwich"), "t_cannibal_sandwich");
      GameRegistry.registerItem(real_cannibal_sandwich = new BirdFood(4, 0.4F, false, "real_cannibal_sandwich"), "real_cannibal_sandwich");
      GameRegistry.registerItem(t_real_cannibal_sandwich = new BirdFood(6, 0.4F, false, "t_real_cannibal_sandwich"), "t_real_cannibal_sandwich");
      GameRegistry.registerItem(chicken_sandwich = new BirdFood(6, 0.7F, false, "chicken_sandwich"), "chicken_sandwich");
      GameRegistry.registerItem(t_chicken_sandwich = new BirdFood(8, 0.7F, false, "t_chicken_sandwich"), "t_chicken_sandwich");
      GameRegistry.registerItem(cheesy_chicken_sandwich = new BirdFood(8, 0.8F, false, "cheesy_chicken_sandwich"), "cheesy_chicken_sandwich");
      GameRegistry.registerItem(t_cheesy_chicken_sandwich = new BirdFood(10, 0.8F, false, "t_cheesy_chicken_sandwich"), "t_cheesy_chicken_sandwich");
      GameRegistry.registerItem(buffalo_chicken_sandwich = new BirdFood(6, 0.9F, false, "buffalo_chicken_sandwich"), "buffalo_chicken_sandwich");
      GameRegistry.registerItem(t_buffalo_chicken_sandwich = new BirdFood(8, 0.9F, false, "t_buffalo_chicken_sandwich"), "t_buffalo_chicken_sandwich");
      GameRegistry.registerItem(cheesy_buffalo_chicken_sandwich = new BirdFood(8, 1.0F, false, "cheesy_buffalo_chicken_sandwich"), "cheesy_buffalo_chicken_sandwich");
      GameRegistry.registerItem(t_cheesy_buffalo_chicken_sandwich = new BirdFood(10, 1.0F, false, "t_cheesy_buffalo_chicken_sandwich"), "t_cheesy_buffalo_chicken_sandwich");
      GameRegistry.registerItem(ham_sandwich = new BirdFood(7, 0.8F, false, "ham_sandwich"), "ham_sandwich");
      GameRegistry.registerItem(t_ham_sandwich = new BirdFood(9, 0.8F, false, "t_ham_sandwich"), "t_ham_sandwich");
      GameRegistry.registerItem(ham_and_cheese_sandwich = new BirdFood(9, 0.9F, false, "ham_and_cheese_sandwich"), "ham_and_cheese_sandwich");
      GameRegistry.registerItem(t_ham_and_cheese_sandwich = new BirdFood(10, 0.9F, false, "t_ham_and_cheese_sandwich"), "t_ham_and_cheese_sandwich");
      GameRegistry.registerItem(chip_sandwich = new BirdFood(6, 0.8F, false, "chip_sandwich"), "chip_sandwich");
      GameRegistry.registerItem(t_chip_sandwich = new BirdFood(8, 0.8F, false, "t_chip_sandwich"), "t_chip_sandwich");
      GameRegistry.registerItem(cheesy_chip_sandwich = new BirdFood(8, 0.8F, false, "cheesy_chip_sandwich"), "cheesy_chip_sandwich");
      GameRegistry.registerItem(t_cheesy_chip_sandwich = new BirdFood(10, 0.8F, false, "t_cheesy_chip_sandwich"), "t_cheesy_chip_sandwich");
      GameRegistry.registerItem(bacone = new BirdFood(12, 0.8F, true, "bacone"), "bacone");
      GameRegistry.registerItem(buckwheat_noodles = new BirdFood(5, 0.6F, false, "buckwheat_noodles"), "buckwheat_noodles");
      GameRegistry.registerItem(beef_soba = new BirdFood(9, 0.9F, false, "beef_soba"), "beef_soba");
      GameRegistry.registerItem(chicken_soba = new BirdFood(8, 0.8F, false, "chicken_soba"), "chicken_soba");
      GameRegistry.registerItem(fish_soba = new BirdFood(8, 0.8F, false, "fish_soba"), "fish_soba");
      GameRegistry.registerItem(veggie_soba = new BirdFood(10, 0.8F, false, "veggie_soba"), "veggie_soba");
      GameRegistry.registerItem(pasta = new BirdFood(6, 0.7F, false, "pasta"), "pasta");
      GameRegistry.registerItem(cincinnati_chili = new BirdFood(13, 1.0F, false, "cincinnati_chili"), "cincinnati_chili");
      GameRegistry.registerItem(mac_and_cheese = new BirdFood(12, 0.9F, false, "mac_and_cheese"), "mac_and_cheese");
      GameRegistry.registerItem(alfredo_sauce = new BirdFood(3, 0.4F, false, "alfredo_sauce"), "alfredo_sauce");
      GameRegistry.registerItem(fettucine_alfredo = new BirdFood(9, 0.8F, false, "fettucine_alfredo"), "fettucine_alfredo");
      GameRegistry.registerItem(chicken_alfredo = new BirdFood(12, 0.9F, false, "chicken_alfredo"), "chicken_alfredo");
      GameRegistry.registerItem(seafood_alfredo = new BirdFood(14, 0.9F, false, "seafood_alfredo"), "seafood_alfredo");
      GameRegistry.registerItem(mushroom_alfredo = new BirdFood(11, 0.9F, false, "mushroom_alfredo"), "mushroom_alfredo");
      GameRegistry.registerItem(squid_ink_pasta = new BirdFood(10, 0.9F, false, "squid_ink_pasta"), "squid_ink_pasta");
      GameRegistry.registerItem(curry_sauce = new BirdFood(3, 0.3F, false, "curry_sauce"), "curry_sauce");
      GameRegistry.registerItem(beef_vindaloo = new BirdFood(12, 0.9F, false, "beef_vindaloo"), "beef_vindaloo");
      GameRegistry.registerItem(lamb_vindaloo = new BirdFood(11, 0.9F, false, "lamb_vindaloo"), "lamb_vindaloo");
      GameRegistry.registerItem(chicken_tikka = new BirdFood(11, 0.9F, false, "chicken_tikka"), "chicken_tikka");
      GameRegistry.registerItem(paneer_tikka = new BirdFood(10, 0.9F, false, "paneer_tikka"), "paneer_tikka");
      GameRegistry.registerItem(pork_curry = new BirdFood(12, 0.9F, false, "pork_curry"), "pork_curry");
      GameRegistry.registerItem(fish_curry = new BirdFood(11, 0.9F, false, "fish_curry"), "fish_curry");
      GameRegistry.registerItem(veg_curry = new BirdFood(10, 0.9F, false, "veg_curry"), "veg_curry");
      GameRegistry.registerItem(pumpkin_curry = new BirdFood(8, 0.9F, false, "pumpkin_curry"), "pumpkin_curry");
      GameRegistry.registerItem(apple_juice = new BirdDrink(4, 0.6F, false, "apple_juice"), "apple_juice");
      GameRegistry.registerItem(carrot_juice = new BirdDrink(3, 0.8F, false, "carrot_juice"), "carrot_juice");
      GameRegistry.registerItem(melon_juice = new BirdDrink(2, 0.6F, false, "melon_juice"), "melon_juice");
      GameRegistry.registerItem(beet_juice = new BirdDrink(2, 0.5F, false, "beet_juice"), "beet_juice");
      GameRegistry.registerItem(cactus_juice = new BirdDrink(2, 0.6F, false, "cactus_juice"), "cactus_juice");
      GameRegistry.registerItem(bottle_of_milk = new BirdDrink(1, 0.4F, false, "bottle_of_milk"), "bottle_of_milk");
      GameRegistry.registerItem(herbal_tea = new BirdDrink(2, 0.9F, false, "herbal_tea"), "herbal_tea");
      GameRegistry.registerItem(sweet_tea = new BirdDrink(3, 0.9F, false, "sweet_tea"), "sweet_tea");
      GameRegistry.registerItem(milk_tea = new BirdDrink(3, 0.9F, false, "milk_tea"), "milk_tea");
      GameRegistry.registerItem(sweet_milk_tea = new BirdDrink(4, 1.0F, false, "sweet_milk_tea"), "sweet_milk_tea");
      GameRegistry.registerItem(iced_tea = new BirdDrink(2, 1.1F, false, "iced_tea"), "iced_tea");
      GameRegistry.registerItem(sweet_iced_tea = new BirdDrink(3, 1.1F, false, "sweet_iced_tea"), "sweet_iced_tea");
      GameRegistry.registerItem(chocolate_milk = new BirdDrink(4, 0.6F, false, "chocolate_milk"), "chocolate_milk");
      GameRegistry.registerItem(hot_chocolate = new BirdDrink(4, 0.8F, false, "hot_chocolate"), "hot_chocolate");
      GameRegistry.registerItem(apple_cider = new BirdDrink(3, 1.0F, false, "apple_cider"), "apple_cider");
      GameRegistry.registerItem(melon_wine = new BirdDrink(3, 1.0F, false, "melon_wine"), "melon_wine");
      GameRegistry.registerItem(beer = new BirdDrink(3, 1.0F, false, "beer"), "beer");
      GameRegistry.registerItem(beet_liquor = new BirdDrink(3, 1.0F, false, "beet_liquor"), "beet_liquor");
      GameRegistry.registerItem(vodka = new BirdDrink(3, 1.0F, false, "vodka"), "vodka");
      GameRegistry.registerItem(poitin = new BirdDrink(3, 1.0F, false, "poitin"), "poitin");
      GameRegistry.registerItem(tequila = new BirdDrink(3, 1.0F, false, "tequila"), "tequila");
      GameRegistry.registerItem(rum = new BirdDrink(3, 1.0F, false, "rum"), "rum");
      GameRegistry.registerItem(umeshu = new BirdDrink(3, 1.0F, false, "umeshu"), "umeshu");
      GameRegistry.registerItem(scumble = new BirdDrink(4, 2.0F, false, "scumble"), "scumble");
      GameRegistry.registerItem(empty_taco = new BirdFood(2, 0.6F, false, "empty_taco"), "empty_taco");
      GameRegistry.registerItem(spiced_beef = new BirdFood(3, 0.1F, false, "spiced_beef"), "spiced_beef");
      GameRegistry.registerItem(spiced_chicken = new BirdFood(3, 0.1F, false, "spiced_chicken"), "spiced_chicken");
      GameRegistry.registerItem(spiced_fish = new BirdFood(2, 0.1F, false, "spiced_fish"), "spiced_fish");
      GameRegistry.registerItem(spiced_pork = new BirdFood(3, 0.2F, false, "spiced_pork"), "spiced_pork");
      GameRegistry.registerItem(spiced_veggies = new BirdFood(4, 0.9F, false, "spiced_veggies"), "spiced_veggies");
      GameRegistry.registerItem(ancho_beef = new BirdFood(5, 0.8F, false, "ancho_beef"), "ancho_beef");
      GameRegistry.registerItem(ancho_chicken = new BirdFood(4, 0.8F, false, "ancho_chicken"), "ancho_chicken");
      GameRegistry.registerItem(ancho_fish = new BirdFood(4, 0.8F, false, "ancho_fish"), "ancho_fish");
      GameRegistry.registerItem(ancho_pork = new BirdFood(5, 0.8F, false, "ancho_pork"), "ancho_pork");
      GameRegistry.registerItem(ancho_veggies = new BirdFood(5, 0.8F, false, "ancho_veggies"), "ancho_veggies");
      GameRegistry.registerItem(beef_taco = new BirdFood(7, 0.8F, false, "beef_taco"), "beef_taco");
      GameRegistry.registerItem(chicken_taco = new BirdFood(6, 0.85F, false, "chicken_taco"), "chicken_taco");
      GameRegistry.registerItem(fish_taco = new BirdFood(6, 0.85F, false, "fish_taco"), "fish_taco");
      GameRegistry.registerItem(pork_taco = new BirdFood(7, 0.8F, false, "pork_taco"), "pork_taco");
      GameRegistry.registerItem(veggie_taco = new BirdFood(7, 0.8F, false, "veggie_taco"), "veggie_taco");
      GameRegistry.registerItem(cheesy_beef_taco = new BirdFood(9, 0.85F, false, "cheesy_beef_taco"), "cheesy_beef_taco");
      GameRegistry.registerItem(cheesy_chicken_taco = new BirdFood(8, 0.9F, false, "cheesy_chicken_taco"), "cheesy_chicken_taco");
      GameRegistry.registerItem(cheesy_pork_taco = new BirdFood(8, 0.9F, false, "cheesy_pork_taco"), "cheesy_pork_taco");
      GameRegistry.registerItem(cheesy_fish_taco = new BirdFood(9, 0.85F, false, "cheesy_fish_taco"), "cheesy_fish_taco");
      GameRegistry.registerItem(cheesy_veggie_taco = new BirdFood(9, 0.85F, false, "cheesy_veggie_taco"), "cheesy_veggie_taco");
      GameRegistry.registerItem(beef_taco_with_cream = new BirdFood(8, 0.85F, false, "beef_taco_with_cream"), "beef_taco_with_cream");
      GameRegistry.registerItem(chicken_taco_with_cream = new BirdFood(7, 0.9F, false, "chicken_taco_with_cream"), "chicken_taco_with_cream");
      GameRegistry.registerItem(pork_taco_with_cream = new BirdFood(7, 0.9F, false, "pork_taco_with_cream"), "pork_taco_with_cream");
      GameRegistry.registerItem(fish_taco_with_cream = new BirdFood(8, 0.85F, false, "fish_taco_with_cream"), "fish_taco_with_cream");
      GameRegistry.registerItem(veggie_taco_with_cream = new BirdFood(8, 0.85F, false, "veggie_taco_with_cream"), "veggie_taco_with_cream");
      GameRegistry.registerItem(beef_taco_with_greens = new BirdFood(10, 0.85F, false, "beef_taco_with_greens"), "beef_taco_with_greens");
      GameRegistry.registerItem(chicken_taco_with_greens = new BirdFood(9, 0.9F, false, "chicken_taco_with_greens"), "chicken_taco_with_greens");
      GameRegistry.registerItem(pork_taco_with_greens = new BirdFood(9, 0.9F, false, "pork_taco_with_greens"), "pork_taco_with_greens");
      GameRegistry.registerItem(fish_taco_with_greens = new BirdFood(10, 0.85F, false, "fish_taco_with_greens"), "fish_taco_with_greens");
      GameRegistry.registerItem(veggie_taco_with_greens = new BirdFood(10, 0.85F, false, "veggie_taco_with_greens"), "veggie_taco_with_greens");
      GameRegistry.registerItem(cheesy_beef_taco_with_cream = new BirdFood(10, 0.85F, false, "cheesy_beef_taco_with_cream"), "cheesy_beef_taco_with_cream");
      GameRegistry.registerItem(cheesy_chicken_taco_with_cream = new BirdFood(9, 0.9F, false, "cheesy_chicken_taco_with_cream"), "cheesy_chicken_taco_with_cream");
      GameRegistry.registerItem(cheesy_pork_taco_with_cream = new BirdFood(9, 0.9F, false, "cheesy_pork_taco_with_cream"), "cheesy_pork_taco_with_cream");
      GameRegistry.registerItem(cheesy_fish_taco_with_cream = new BirdFood(10, 0.85F, false, "cheesy_fish_taco_with_cream"), "cheesy_fish_taco_with_cream");
      GameRegistry.registerItem(cheesy_veggie_taco_with_cream = new BirdFood(10, 0.85F, false, "cheesy_veggie_taco_with_cream"), "cheesy_veggie_taco_with_cream");
      GameRegistry.registerItem(cheesy_beef_taco_with_greens = new BirdFood(12, 0.85F, false, "cheesy_beef_taco_with_greens"), "cheesy_beef_taco_with_greens");
      GameRegistry.registerItem(cheesy_chicken_taco_with_greens = new BirdFood(11, 0.9F, false, "cheesy_chicken_taco_with_greens"), "cheesy_chicken_taco_with_greens");
      GameRegistry.registerItem(cheesy_pork_taco_with_greens = new BirdFood(11, 0.9F, false, "cheesy_pork_taco_with_greens"), "cheesy_pork_taco_with_greens");
      GameRegistry.registerItem(cheesy_fish_taco_with_greens = new BirdFood(11, 0.85F, false, "cheesy_fish_taco_with_greens"), "cheesy_fish_taco_with_greens");
      GameRegistry.registerItem(cheesy_veggie_taco_with_greens = new BirdFood(11, 0.85F, false, "cheesy_veggie_taco_with_greens"), "cheesy_veggie_taco_with_greens");
      GameRegistry.registerItem(beef_taco_with_cream_and_greens = new BirdFood(11, 0.85F, false, "beef_taco_with_cream_and_greens"), "beef_taco_with_cream_and_greens");
      GameRegistry.registerItem(chicken_taco_with_cream_and_greens = new BirdFood(10, 0.8F, false, "chicken_taco_with_cream_and_greens"), "chicken_taco_with_cream_and_greens");
      GameRegistry.registerItem(pork_taco_with_cream_and_greens = new BirdFood(10, 0.8F, false, "pork_taco_with_cream_and_greens"), "pork_taco_with_cream_and_greens");
      GameRegistry.registerItem(fish_taco_with_cream_and_greens = new BirdFood(11, 0.85F, false, "fish_taco_with_cream_and_greens"), "fish_taco_with_cream_and_greens");
      GameRegistry.registerItem(veggie_taco_with_cream_and_greens = new BirdFood(11, 0.85F, false, "veggie_taco_with_cream_and_greens"), "veggie_taco_with_cream_and_greens");
      GameRegistry.registerItem(beef_taco_supreme = new BirdFood(14, 1.0F, false, "beef_taco_supreme"), "beef_taco_supreme");
      GameRegistry.registerItem(chicken_taco_supreme = new BirdFood(14, 1.0F, false, "chicken_taco_supreme"), "chicken_taco_supreme");
      GameRegistry.registerItem(pork_taco_supreme = new BirdFood(14, 1.0F, false, "pork_taco_supreme"), "pork_taco_supreme");
      GameRegistry.registerItem(fish_taco_supreme = new BirdFood(14, 1.0F, false, "fish_taco_supreme"), "fish_taco_supreme");
      GameRegistry.registerItem(veggie_taco_supreme = new BirdFood(14, 1.0F, false, "veggie_taco_supreme"), "veggie_taco_supreme");
      GameRegistry.registerItem(breakfast_burrito = new BirdFood(10, 1.0F, false, "breakfast_burrito"), "breakfast_burrito");
      GameRegistry.registerItem(taako = new BirdFood(20, 1.0F, false, "taako"), "taako");
      GameRegistry.registerItem(chocolate_bar = new BirdFood(3, 0.3F, false, "chocolate_bar"), "chocolate_bar");
      GameRegistry.registerItem(ice_cream = new BirdFood(4, 0.4F, false, "ice_cream"), "ice_cream");
      GameRegistry.registerItem(hot_fudge = new BirdFood(3, 0.3F, false, "hot_fudge"), "hot_fudge");
      GameRegistry.registerItem(ice_cream_sundae = new BirdFood(6, 0.9F, false, "ice_cream_sundae"), "ice_cream_sundae");
      GameRegistry.registerItem(apple_pie = new BirdFood(14, 1.0F, false, "apple_pie"), "apple_pie");
      GameRegistry.registerItem(apple_pie_a_la_mode = new BirdFood(15, 1.1F, false, "apple_pie_a_la_mode"), "apple_pie_a_la_mode");
      GameRegistry.registerItem(astronaut_ice_cream = new BirdFood(4, 0.5F, false, "astronaut_ice_cream"), "astronaut_ice_cream");
      GameRegistry.registerItem(plum_pudding = new BirdFood(10, 1.2F, false, "plum_pudding"), "plum_pudding");
      GameRegistry.registerItem(pumpkin_spice_latte = new BirdDrink(5, 0.8F, false, "pumpkin_spice_latte"), "pumpkin_spice_latte");
      GameRegistry.registerItem(pumpkin_bread = new BirdFood(5, 0.8F, false, "pumpkin_bread"), "pumpkin_bread");
      GameRegistry.registerItem(shortbread_cookie = new BirdFood(1, 0.1F, false, "shortbread_cookie"), "shortbread_cookie");
      GameRegistry.registerItem(cookie_dough = new BirdFood(3, 0.1F, false, "cookie_dough"), "cookie_dough");
      GameRegistry.registerItem(ice_cream_bacone = new BirdFood(15, 0.9F, false, "ice_cream_bacone"), "ice_cream_bacone");
      initItems();
   }

   public static void initModels() {
      Item[] var10000 = new Item[]{yogurt, cheese, cooked_egg, gravy, fish_and_chips, sunflower_seeds, roasted_pumpkin_seeds, fugu, sashimi, molasses, butter, jam, stuffed_potato, smothered_potato, raw_crisps, crisps, beef_jerky, cold_chips, hot_chips, mashed_potato, mashed_potato_gravy, cheese_fries, chili_fries, chili_cheese_fries, poutine, hotcakes, hotcakes_with_syrup, choc_hotcakes, choc_hotcakes_syrup, berry_hotcakes, berry_hotcakes_syrup, bacon_pancakes, bacon_pancakes_syrup, waffles, waffles_syrup, choc_waffles, choc_waffles_syrup, berry_waffles, berry_waffles_syrup, dandelion_salad, spring_salad, cobb_salad, fruit_salad, potato_salad, grilled_melon, sliced_cactus, grilled_cactus, grilled_pumpkin, sliced_beets, roast_beets, candied_beets, cooked_carrot, baked_apple, rabbit_pie, chicken_pot_pie, shepherds_pie, fish_pie, cottage_pie, veg_pie, quiche, mushroom_quiche, bacon_quiche, fish_quiche, green_quiche, beef_stew, veg_stew, pumpkin_soup, potato_soup, chicken_noodle_soup, chili, hot_chili, pizza, meat_pizza, veg_pizza, pizza_supreme, raw_bacon, bacon, sliced_lamb, chopped_chicken, raw_fingers, chicken_fingers, raw_barbecue_pork, barbecue_pork, raw_barbecue_chicken, barbecue_chicken, ground_beef, burger, sliced_steak, veggie_meat, raw_fish_sticks, fish_sticks, fish_fillet, buffalo_chicken, sliced_ham, empty_sandwich, toast, buttered_toast, jammy_toast, jammy_buttered_toast, pita, chicken_salad, t_chicken_salad, egg_salad, t_egg_salad, fish_salad, t_fish_salad, cheese_sandwich, t_cheese_sandwich, egg_sandwich, t_egg_sandwich, bacon_sandwich, t_bacon_sandwich, bacon_and_cheese_sandwich, t_bacon_and_cheese_sandwich, egg_and_cheese_sandwich, t_egg_and_cheese_sandwich, bacon_and_egg_sandwich, t_bacon_and_egg_sandwich, bacon_egg_and_cheese_sandwich, t_bacon_egg_and_cheese_sandwich, pork_bbq_sandwich, t_pork_bbq_sandwich, chicken_bbq_sandwich, t_chicken_bbq_sandwich, hamburger, t_hamburger, bacon_hamburger, t_bacon_hamburger, cheeseburger, t_cheeseburger, bacon_cheeseburger, t_bacon_cheeseburger, steak_sandwich, t_steak_sandwich, cheesesteak, t_cheesesteak, veggie_hamburger, t_veggie_hamburger, veggie_cheeseburger, t_veggie_cheeseburger, veg_sandwich, t_veg_sandwich, cheesy_veg_sandwich, t_cheesy_veg_sandwich, gyro, veggie_gyro, dagwood, cannibal_sandwich, t_cannibal_sandwich, real_cannibal_sandwich, t_real_cannibal_sandwich, chicken_sandwich, t_chicken_sandwich, cheesy_chicken_sandwich, t_cheesy_chicken_sandwich, buffalo_chicken_sandwich, t_buffalo_chicken_sandwich, cheesy_buffalo_chicken_sandwich, t_cheesy_buffalo_chicken_sandwich, ham_sandwich, t_ham_sandwich, ham_and_cheese_sandwich, t_ham_and_cheese_sandwich, chip_sandwich, t_chip_sandwich, cheesy_chip_sandwich, t_cheesy_chip_sandwich, bacone, buckwheat_noodles, beef_soba, chicken_soba, fish_soba, veggie_soba, pasta, cincinnati_chili, mac_and_cheese, alfredo_sauce, fettucine_alfredo, chicken_alfredo, seafood_alfredo, mushroom_alfredo, squid_ink_pasta, curry_sauce, beef_vindaloo, lamb_vindaloo, chicken_tikka, paneer_tikka, pork_curry, fish_curry, veg_curry, pumpkin_curry, apple_juice, carrot_juice, melon_juice, beet_juice, cactus_juice, bottle_of_milk, herbal_tea, sweet_tea, milk_tea, sweet_milk_tea, iced_tea, sweet_iced_tea, chocolate_milk, hot_chocolate, apple_cider, melon_wine, beer, beet_liquor, vodka, poitin, tequila, rum, umeshu, scumble, empty_taco, spiced_beef, spiced_chicken, spiced_fish, spiced_pork, spiced_veggies, ancho_beef, ancho_chicken, ancho_fish, ancho_pork, ancho_veggies, beef_taco, chicken_taco, fish_taco, pork_taco, veggie_taco, cheesy_beef_taco, cheesy_chicken_taco, cheesy_pork_taco, cheesy_fish_taco, cheesy_veggie_taco, beef_taco_with_cream, chicken_taco_with_cream, pork_taco_with_cream, fish_taco_with_cream, veggie_taco_with_cream, beef_taco_with_greens, chicken_taco_with_greens, pork_taco_with_greens, fish_taco_with_greens, veggie_taco_with_greens, cheesy_beef_taco_with_cream, cheesy_chicken_taco_with_cream, cheesy_pork_taco_with_cream, cheesy_fish_taco_with_cream, cheesy_veggie_taco_with_cream, cheesy_beef_taco_with_greens, cheesy_chicken_taco_with_greens, cheesy_pork_taco_with_greens, cheesy_fish_taco_with_greens, cheesy_veggie_taco_with_greens, beef_taco_with_cream_and_greens, chicken_taco_with_cream_and_greens, pork_taco_with_cream_and_greens, fish_taco_with_cream_and_greens, veggie_taco_with_cream_and_greens, beef_taco_supreme, chicken_taco_supreme, pork_taco_supreme, fish_taco_supreme, veggie_taco_supreme, breakfast_burrito, taako, chocolate_bar, ice_cream, hot_fudge, ice_cream_sundae, apple_pie, apple_pie_a_la_mode, astronaut_ice_cream, plum_pudding, pumpkin_spice_latte, pumpkin_bread, shortbread_cookie, cookie_dough, ice_cream_bacone};
   }
}
